(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.RouteSummarizationEngine=api;})(typeof self!=='undefined'?self:this,function(){
 'use strict';
 var IPV4=32,IPV6=128;
 function fail(code){var e=new Error(code);e.code=code;throw e;}
 function parseIPv4(text){if(typeof text!=='string')fail('address_type_invalid');var p=text.split('.');if(p.length!==4)fail('ipv4_address_invalid');var n=0;for(var i=0;i<4;i++){if(!/^\d{1,3}$/.test(p[i])||Number(p[i])>255)fail('ipv4_address_invalid');n=(n<<8)+Number(p[i]);}return BigInt(n>>>0);}
 function parseIPv6(text){if(typeof text!=='string'||text.indexOf(':')<0)fail('ipv6_address_invalid');var value=text.toLowerCase();var halves=value.split('::');if(halves.length>2)fail('ipv6_address_invalid');var left=halves[0]?halves[0].split(':').filter(Boolean):[],right=halves.length===2&&halves[1]?halves[1].split(':').filter(Boolean):[];if(left.some(function(x){return !/^[0-9a-f]{1,4}$/.test(x);})||right.some(function(x){return !/^[0-9a-f]{1,4}$/.test(x);}))fail('ipv6_address_invalid');var missing=8-left.length-right.length;if((halves.length===1&&missing!==0)||missing<0)fail('ipv6_address_invalid');var groups=left.concat(Array(missing).fill('0'),right),n=0n;groups.forEach(function(g){n=(n<<16n)+BigInt(parseInt(g||'0',16));});return n;}
 function formatIPv4(n){var x=Number(n);return [(x>>>24)&255,(x>>>16)&255,(x>>>8)&255,x&255].join('.');}
 function formatIPv6(n){var g=[];for(var i=7;i>=0;i--)g.push(Number((n>>BigInt(i*16))&65535n).toString(16));var bs=-1,bl=0,start=-1;for(i=0;i<=8;i++){if(i<8&&g[i]==='0'){if(start<0)start=i;}else if(start>=0){if(i-start>bl){bs=start;bl=i-start;}start=-1;}}if(bl<2)bs=-1;var parts=[];for(i=0;i<8;i++){if(i===bs){parts.push('');i+=bl-1;if(i===7)parts.push('');}else parts.push(g[i]);}return parts.join(':').replace(/^:/,'::').replace(/:$/,'::').replace(/:::/g,'::');}
 function mask(bits,prefix){return prefix===0?0n:((1n<<BigInt(prefix))-1n)<<BigInt(bits-prefix);}
 function parsePrefix(value){if(typeof value!=='string')fail('prefix_type_invalid');var slash=value.indexOf('/');if(slash<1||slash===value.length-1)fail('prefix_format_invalid');var address=value.slice(0,slash),raw=value.slice(slash+1),family,bits,number;if(!/^\d+$/.test(raw))fail('prefix_length_invalid');if(address.indexOf(':')>=0){family='ipv6';bits=IPV6;number=parseIPv6(address);}else{family='ipv4';bits=IPV4;number=parseIPv4(address);}var prefix=Number(raw);if(prefix<0||prefix>bits)fail('prefix_length_invalid');var network=number&mask(bits,prefix);return {family:family,bits:bits,prefix:prefix,network:network,canonical:(family==='ipv4'?formatIPv4(network):formatIPv6(network))+'/'+prefix};}
 function makePrefix(family,network,prefix){var bits=family==='ipv4'?IPV4:IPV6;return {family:family,bits:bits,prefix:prefix,network:network,canonical:(family==='ipv4'?formatIPv4(network):formatIPv6(network))+'/'+prefix};}
 function contains(a,b){return a.family===b.family&&a.prefix<=b.prefix&&(b.network&mask(b.bits,a.prefix))===a.network;}
 function siblings(a,b){return a.family===b.family&&a.prefix===b.prefix&&a.prefix>0&&((a.network&mask(a.bits,a.prefix-1))===(b.network&mask(b.bits,b.prefix-1)))&&a.network!==b.network;}
 function sortPrefixes(items){return items.slice().sort(function(a,b){return a.family.localeCompare(b.family)||a.prefix-b.prefix||(a.network<b.network?-1:a.network>b.network?1:0);});}
 function aggregate(items,minPrefix){var current=sortPrefixes(items),changed=true;while(changed){changed=false;var out=[];for(var i=0;i<current.length;i++){var a=current[i],b=current[i+1];if(b&&a.prefix>b.prefix&&contains(a,b)){out.push(a);i++;continue;}if(b&&a.prefix===b.prefix&&a.prefix>minPrefix&&siblings(a,b)){out.push(makePrefix(a.family,a.network&mask(a.bits,a.prefix-1),a.prefix-1));i++;changed=true;}else out.push(a);}current=sortPrefixes(out);}return current;}
 function summarize(input,options){options=options||{};if(!input||typeof input!=='object'||Array.isArray(input))return {status:'invalid',errors:['input_type_invalid'],prefixes:[],summaries:[],covered:[],redundant:[],recommendations:[]};var values=Array.isArray(input.prefixes)?input.prefixes:input.prefixes===undefined?[]:null;if(values===null)return {status:'invalid',errors:['prefixes_type_invalid'],prefixes:[],summaries:[],covered:[],redundant:[],recommendations:[]};var errors=[],parsed=[];values.forEach(function(v,i){try{parsed.push(parsePrefix(v));}catch(e){errors.push('prefix_'+(i+1)+'_'+e.code);}});var minPrefix=options.minPrefixLength===undefined?0:Number(options.minPrefixLength);if(!Number.isInteger(minPrefix)||minPrefix<0||minPrefix>128)errors.push('min_prefix_invalid');var unique=[],redundant=[];sortPrefixes(parsed).forEach(function(p){if(unique.some(function(x){return contains(x,p);})){redundant.push(p.canonical);return;}for(var i=unique.length-1;i>=0;i--)if(contains(p,unique[i])){redundant.push(unique[i].canonical);unique.splice(i,1);}unique.push(p);});var summaries=errors.length?[]:aggregate(unique,minPrefix),recommendations=[];if(redundant.length)recommendations.push('Remove duplicate or already-covered prefixes before publishing a route summary.');if(summaries.length<unique.length)recommendations.push('The listed prefixes can be advertised as a smaller set of aggregate routes.');if(!recommendations.length&&summaries.length)recommendations.push('Verify the aggregate does not include unintended address space and confirm longer-prefix exceptions.');return {status:errors.length?'invalid':summaries.length?'ready':'empty',errors:errors,prefixes:parsed.map(function(p){return p.canonical;}),summaries:summaries.map(function(p){return p.canonical;}),covered:parsed.filter(function(p){return summaries.some(function(s){return contains(s,p);});}).map(function(p){return p.canonical;}),redundant:redundant,uniqueCount:unique.length,inputCount:parsed.length,reduction:unique.length-summaries.length,reductionPercent:unique.length?Number(((unique.length-summaries.length)/unique.length*100).toFixed(1)):0,familyCounts:{ipv4:summaries.filter(function(p){return p.family==='ipv4';}).length,ipv6:summaries.filter(function(p){return p.family==='ipv6';}).length},recommendations:recommendations};}
 function calculate(input,options){return summarize(input,options||{});}function professionalReport(input,meta){meta=meta||{};return {schemaVersion:'route-summarization-engineering-report/1.0',tool:'NetEngineerLab Route Summarization Calculator',project:meta.project||'Untitled',generatedAt:new Date().toISOString(),input:input,result:summarize(input,meta.options),assumptions:['Input prefixes are normalized to network boundaries','IPv4 and IPv6 are summarized independently','Route aggregation may cover unused address space and requires topology review']};}
 return {parsePrefix:parsePrefix,formatIPv4:formatIPv4,formatIPv6:formatIPv6,summarize:summarize,calculate:calculate,professionalReport:professionalReport};
});
