/** NetEngineerLab V2.1-Transport-Tool-33 | Modified 2026-09-10 15:10:00 */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.NELTransmissionRingEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function parseDemands(text,nodeCount){const out=[];String(text||'').split(/\n+/).forEach((line,idx)=>{line=line.trim();if(!line)return;const p=line.split(/[,;\t]+/).map(x=>x.trim());if(p.length<3)throw new Error('demand_format_'+(idx+1));const s=Number(p[0]),d=Number(p[1]),g=Number(p[2]);if(!Number.isInteger(s)||!Number.isInteger(d)||s<1||d<1||s>nodeCount||d>nodeCount||s===d||!(g>0))throw new Error('demand_value_'+(idx+1));out.push({source:s-1,dest:d-1,gbps:g,priority:(p[3]||'normal').toLowerCase()});});return out;}
function cwPath(n,s,d){const links=[];let x=s;while(x!==d){links.push(x);x=(x+1)%n;}return links;}
function ccwPath(n,s,d){const links=[];let x=s;while(x!==d){x=(x-1+n)%n;links.push(x);}return links;}
function containsFailed(path,failed){return failed==null?false:path.includes(failed);}
function routeDemand(n,d,failed){const a=cwPath(n,d.source,d.dest),b=ccwPath(n,d.source,d.dest);const aa=!containsFailed(a,failed),bb=!containsFailed(b,failed);if(!aa&&!bb)return[];if(aa&&!bb)return [{path:a,fraction:1}];if(bb&&!aa)return [{path:b,fraction:1}];if(a.length<b.length)return [{path:a,fraction:1}];if(b.length<a.length)return [{path:b,fraction:1}];return [{path:a,fraction:.5},{path:b,fraction:.5}];}
function simulate(n,demands,capacities,failed=null){const loads=Array(n).fill(0);let dropped=0;for(const d of demands){const rs=routeDemand(n,d,failed);if(!rs.length){dropped+=d.gbps;continue;}for(const r of rs)for(const link of r.path)loads[link]+=d.gbps*r.fraction;}const util=loads.map((x,i)=>capacities[i]>0?x/capacities[i]*100:Infinity);let max=0,idx=0;util.forEach((u,i)=>{if(u>max){max=u;idx=i;}});return{loads,util,maxUtilPct:max,bottleneckLink:idx,droppedGbps:dropped,avgUtilPct:util.reduce((a,b)=>a+b,0)/util.length};}
function calculate(i={}){const errors=[],warnings=[];const nodeCount=Math.floor(num(i.nodeCount,8));const cap=num(i.linkCapacityGbps,100);const limit=clamp(num(i.maxPlanningUtilPct,80),10,100);const upgradeFactor=clamp(num(i.upgradeFactor,2),1,10);if(nodeCount<3||nodeCount>64)errors.push('nodeCount');if(!(cap>0))errors.push('capacity');let demands=[];try{demands=parseDemands(i.demandsText,nodeCount);}catch(e){errors.push(e.message);}if(!demands.length)errors.push('demands');if(errors.length)return{ok:false,errors,warnings};const caps=Array(nodeCount).fill(cap);const normal=simulate(nodeCount,demands,caps,null);let worst={maxUtilPct:-1};const matrix=[];for(let f=0;f<nodeCount;f++){const s=simulate(nodeCount,demands,caps,f);matrix.push({failedLink:f,...s});if(s.maxUtilPct>worst.maxUtilPct)worst={failedLink:f,...s};}
const liveBottleneck=worst.bottleneckLink;const upgraded=[...caps];upgraded[liveBottleneck]*=upgradeFactor;let afterWorst={maxUtilPct:-1};for(let f=0;f<nodeCount;f++){const s=simulate(nodeCount,demands,upgraded,f);if(s.maxUtilPct>afterWorst.maxUtilPct)afterWorst={failedLink:f,...s};}
const totalTrafficGbps=demands.reduce((a,d)=>a+d.gbps,0);const normalOver=normal.util.filter(u=>u>limit).length;const failureOver=matrix.filter(x=>x.maxUtilPct>limit).length;let riskScore=0;riskScore+=Math.min(45,Math.max(0,worst.maxUtilPct-limit)*1.5);riskScore+=failureOver/nodeCount*30;if(normal.maxUtilPct>limit)riskScore+=15;if(nodeCount>12)riskScore+=10;if(demands.some(d=>d.priority==='critical')&&failureOver)riskScore+=10;riskScore=Math.round(clamp(riskScore,0,100));let risk='low';if(riskScore>=70)risk='critical';else if(riskScore>=45)risk='high';else if(riskScore>=20)risk='medium';if(worst.maxUtilPct>100)warnings.push('failureOverload');if(normal.maxUtilPct>limit)warnings.push('normalCongestion');if(nodeCount>12)warnings.push('largeRing');const suggestions=[];if(worst.maxUtilPct>limit)suggestions.push('upgradeBottleneck');if(nodeCount>12)suggestions.push('splitRingReview');if(failureOver>0)suggestions.push('rerouteOrMigrate');if(!suggestions.length)suggestions.push('monitor');return{ok:true,errors,warnings,nodeCount,totalTrafficGbps,planningLimitPct:limit,normal,worstFailure:worst,failureMatrix:matrix,failureScenariosOverLimit:failureOver,normalLinksOverLimit:normalOver,riskScore,risk,suggestions,optimization:{targetLink:liveBottleneck,upgradeFactor,beforeWorstUtilPct:worst.maxUtilPct,afterWorstUtilPct:afterWorst.maxUtilPct,improvementPct:worst.maxUtilPct-afterWorst.maxUtilPct}};}
return{calculate,parseDemands,simulate};
});
