/**
 * NetEngineerLab
 * Version: V2.1-Flagship-V1.1-UX-Audit
 * Modified: 2026-09-05 18:04:06
 * Purpose: Productized flagship UX with first-use engineer audit refinements for Network Change Planner & MOP Generator.
 */
(function(){
  "use strict";
  const E=window.NELNetworkChangePlanner;if(!E)return;
  const zh=window.NEL_LANG==="zh";
  const $=id=>document.getElementById(id);
  let current=null,lastEvaluation=null;
  const status=$("plannerStatus"),risk=$("riskCard"),diff=$("semanticDiff"),forward=$("forwardConfig"),rollback=$("rollbackConfig"),runbook=$("runbookList"),verify=$("verificationPanel");
  const t=(en,cn)=>zh?cn:en;
  const riskText={
    NEW_AGGREGATE:t("Creates a new logical aggregate. Confirm the ID is unused and both ends are coordinated.","将创建新的逻辑聚合口。请确认聚合ID未占用，并协调链路两端配置。"),
    MEMBERS_ADDED:t("Adds physical members to the bundle. A wrong member can affect an existing uplink.","向聚合组新增物理成员。选错成员口可能影响现有上联。"),
    MEMBERS_REMOVED:t("Removes existing members and reduces available bundle capacity during the change.","从聚合组移除现有成员，变更期间可能降低可用带宽和冗余。"),
    VLANS_REMOVED:t("Removes VLAN reachability from the trunk and may interrupt dependent services.","从Trunk删除VLAN，可能中断依赖该VLAN的业务。"),
    VLANS_ADDED:t("Extends Layer-2 reachability. Confirm the VLAN is intended and present end-to-end.","扩展二层VLAN可达范围。请确认该VLAN确实需要，并已在端到端路径存在。"),
    NATIVE_VLAN_CHANGE:t("Changes untagged/PVID behavior. Mismatch across the link can create traffic leakage or loss.","修改Native VLAN/PVID行为。链路两端不一致可能导致流量错投或中断。"),
    DESCRIPTION_CHANGE:t("Documentation-only change with low forwarding impact.","仅修改接口描述，对转发影响较低。"),
    OPAQUE_CONTEXT:t("The snapshot contains unmanaged lines. Review nearby configuration before execution.","现网快照包含未受管配置。执行前应检查相关上下文。"),
    BLOCKED_CONFLICT:t("A blocking conflict was detected. Do not execute until it is resolved.","检测到阻断性冲突。在冲突解决前不要执行变更。")
  };
  const scenarios=[
    {id:"cisco-stack-vlan",name:t("Cisco stack uplink: add VLAN 100","Cisco 堆叠上联：新增 VLAN 100"),deviceId:"cisco-c9200l-24t-4g",aggregateId:10,lagMode:"lacp",members:[1,2],ports:[1,1],allowed:"10,20,30,99,100",native:99,description:"CORE-UPLINK-NEW",note:t("Two C9200L stack members each contribute one uplink to Port-channel10. VLAN 100 is added while preserving the existing native VLAN.","两台 C9200L 堆叠成员各提供一个上联口组成 Port-channel10，在保持 Native VLAN 99 的同时新增 VLAN 100。")},
    {id:"huawei-campus",name:t("Huawei campus uplink: expand trunk","华为园区上联：扩展 Trunk VLAN"),deviceId:"huawei-s5735-l24t4s-a1",aggregateId:10,lagMode:"lacp",members:[1,1],ports:[25,26],allowed:"10,20,30,99,100",native:99,description:"CORE-UPLINK-NEW",note:t("A dual-link S5735 uplink keeps Eth-Trunk10 and expands the allowed VLAN set with a minimal delta.","S5735 双链路上联保持 Eth-Trunk10，仅通过最小变更扩展允许通过的 VLAN。")},
    {id:"juniper-vc",name:t("Juniper VC: ae10 trunk normalization","Juniper VC：ae10 Trunk 对齐"),deviceId:"juniper-ex3400-24t",aggregateId:10,lagMode:"lacp",members:[0,1],ports:[0,0],allowed:"10,20,30,99,100",native:99,description:"CORE-UPLINK-NEW",note:t("Two EX3400 Virtual Chassis members form ae10. The plan reconciles trunk membership and description without rebuilding correct state.","两台 EX3400 Virtual Chassis 成员组成 ae10，规划器仅修正 Trunk VLAN 和描述，不重建已正确的状态。")},
    {id:"arista-dc",name:t("Arista DC uplink: controlled VLAN expansion","Arista 数据中心上联：受控扩展 VLAN"),deviceId:"arista-7050sx3-48yc8",aggregateId:10,lagMode:"lacp",members:[1,1],ports:[49,50],allowed:"10,20,30,99,100",native:99,description:"LEAF-UPLINK-NEW",note:t("A 7050SX3 Port-Channel change demonstrates the same intent workflow on a data-center switching platform.","在 7050SX3 Port-Channel 上应用同一套意图变更流程，验证数据中心交换平台的一致体验。")}
  ];
  const devices=Object.entries(E.DEVICES);for(const [id,d] of devices){const o=document.createElement("option");o.value=id;o.textContent=d.label;$("deviceId").appendChild(o)}
  scenarios.forEach(s=>{const o=document.createElement("option");o.value=s.id;o.textContent=s.name;$("scenarioSelect").appendChild(o)});
  function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
  function syncDevice(loadSample=true){const d=E.DEVICES[$("deviceId").value];$("member1").value=d.memberDefault;$("member2").value=d.vendor==="cisco-ios"||d.vendor==="juniper-junos"?d.memberDefault+1:d.memberDefault;$("port1").value=d.portStart;$("port2").value=Math.min(d.portEnd,d.portStart+1);$("portHint").textContent=`${d.label}: member 0-${d.memberMax}, port ${d.portStart}-${d.portEnd}`;if(loadSample)$("runningConfig").value=E.samples[d.vendor]||"";updateInputChecklist();}
  $("deviceId").addEventListener("change",()=>syncDevice(true));
  function applyScenario(id){const s=scenarios.find(x=>x.id===id);if(!s)return;$("deviceId").value=s.deviceId;syncDevice(true);$("aggregateId").value=s.aggregateId;$("lagMode").value=s.lagMode;$("member1").value=s.members[0];$("member2").value=s.members[1];$("port1").value=s.ports[0];$("port2").value=s.ports[1];$("allowedVlans").value=s.allowed;$("nativeVlan").value=s.native;$("description").value=s.description;$("scenarioNote").textContent=s.note;status.innerHTML=`${badge("ready")} ${t("Example loaded — review the highlighted inputs before building a plan.","已载入示例——生成计划前请先核对输入，并在真实变更时替换现网配置。")}`;updateInputChecklist();}
  $("scenarioSelect").addEventListener("change",e=>applyScenario(e.target.value));
  function input(){return {deviceId:$("deviceId").value,aggregateId:$("aggregateId").value,lagMode:$("lagMode").value,members:[{member:$("member1").value,port:$("port1").value},{member:$("member2").value,port:$("port2").value}],allowedVlans:$("allowedVlans").value,nativeVlan:$("nativeVlan").value,description:$("description").value,runningConfig:$("runningConfig").value};}
  function badge(v){return `<span class="status-badge ${esc(v)}">${esc(String(v).toUpperCase())}</span>`}
  function updateInputChecklist(){const cfg=$("runningConfig").value.trim(),members=[$("port1").value,$("port2").value].every(Boolean),vlans=$("allowedVlans").value.trim(),native=$("nativeVlan").value,nativeOk=native===""||vlans.split(/[\s,]+/).includes(String(native));const rows=[[!!cfg,t("Running config pasted","已粘贴现网配置")],[members,t("Two aggregate members selected","已选择两个聚合成员")],[!!vlans,t("Allowed VLAN set defined","已定义允许 VLAN")],[nativeOk,t("Native/PVID is included in allowed VLANs","Native/PVID 已包含在允许 VLAN 中")]];$("inputChecklist").innerHTML=rows.map(([ok,label])=>`<li class="${ok?"ok":"pending"}"><span>${ok?"✓":"•"}</span>${esc(label)}</li>`).join("");$("step2")?.classList.toggle("complete",members&&!!vlans&&nativeOk);const step1=document.querySelector(".product-guide .guide-step:first-child");step1?.classList.toggle("complete",!!cfg);}
  ["runningConfig","member1","member2","port1","port2","allowedVlans","nativeVlan","aggregateId"].forEach(id=>$(id)?.addEventListener("input",updateInputChecklist));
  function renderRisk(p){const factors=p.risk.factors||[];risk.innerHTML=`<div class="metric"><b>${p.risk.score}</b><span>${t("Risk score","风险评分")}</span></div><div><strong>${esc(p.risk.band.toUpperCase())}</strong><p>${factors.length?t("Expand the reasons below before approving the change.","执行前请展开并检查以下风险原因。") : t("Current managed state already matches the desired intent.","当前受管状态已经与目标意图一致。")}</p></div>`;$("riskReasons").innerHTML=factors.length?factors.map(x=>`<details><summary><span>${esc(x.code)}</span><b>+${x.points}</b></summary><p>${esc(riskText[x.code]||t("Review this risk factor before execution.","执行前请审查该风险因素。"))}</p></details>`).join(""):`<div class="empty-state">${t("No incremental risk factors were added.","没有新增风险因素。")}</div>`;}
  function explainPlan(p){const s=p.reconciliation.semantic,parts=[];if(p.status==="noop")parts.push(t("The managed running state already matches the requested intent. No configuration commands are required.","当前受管现网状态已经与目标意图一致，无需下发配置命令。"));else if(p.status==="blocked")parts.push(t("The plan is blocked by a conflict. Resolve the conflict before generating an execution window.","当前计划存在阻断性冲突，应先解决冲突再进入实施窗口。"));else{parts.push(t(`The planner will change ${s.members.added.length+s.members.removed.length} member binding(s) and ${s.vlans.added.length+s.vlans.removed.length} VLAN membership item(s).`,`规划器将调整 ${s.members.added.length+s.members.removed.length} 个成员绑定和 ${s.vlans.added.length+s.vlans.removed.length} 个 VLAN 成员项。`));if(s.native.changed)parts.push(t(`Native/PVID changes from ${s.native.before??"none"} to ${s.native.after??"none"}; verify both ends of the link.`,`Native/PVID 将从 ${s.native.before??"无"} 变为 ${s.native.after??"无"}，必须核对链路两端一致性。`));if(p.risk.requiresPeerReview)parts.push(t("Risk threshold requires peer review and a controlled maintenance window.","风险阈值要求进行同伴复核，并在受控维护窗口实施。"));else parts.push(t("Risk is below the peer-review threshold, but normal change approval still applies.","风险低于强制同伴复核阈值，但仍应执行正常变更审批。"));}
    $("resultExplanation").innerHTML=parts.map((x,i)=>`<p><span>${i+1}</span>${esc(x)}</p>`).join("");}
  function mopMarkdown(p,evaluation){const d=p.desired,r=p.risk;const sem=p.reconciliation.semantic;const lines=[`# ${t("Network Change Method of Procedure","网络变更 MOP / 实施方案")}`,"",`- ${t("Device","设备")}: ${E.DEVICES[d.deviceId].label}`,`- ${t("Vendor","厂商")}: ${d.vendor}`,`- ${t("Logical aggregate","逻辑聚合口")}: ${d.logical}`,`- ${t("Risk","风险")}: ${r.score}/100 (${r.band.toUpperCase()})`,`- ${t("Plan status","计划状态")}: ${p.status.toUpperCase()}`,"",`## ${t("Change scope","变更范围")}`,`- ${t("Members","成员口")}: ${d.members.join(", ")}`,`- ${t("Allowed VLANs","允许 VLAN")}: ${d.allowedVlans.join(", ")}`,`- Native/PVID: ${d.nativeVlan??"—"}`,`- Description: ${d.description||"—"}`,"",`## ${t("Semantic delta","语义差异")}`,`- ${t("Members added","新增成员")}: ${sem.members.added.join(", ")||"—"}`,`- ${t("Members removed","移除成员")}: ${sem.members.removed.join(", ")||"—"}`,`- ${t("VLANs added","新增 VLAN")}: ${sem.vlans.added.join(", ")||"—"}`,`- ${t("VLANs removed","移除 VLAN")}: ${sem.vlans.removed.join(", ")||"—"}`,"",`## ${t("Risk reasons","风险原因")}`];
    (r.factors.length?r.factors:[{code:t("No incremental factors","无新增风险因素"),points:0}]).forEach(x=>lines.push(`- ${x.code}: +${x.points}${riskText[x.code]?` — ${riskText[x.code]}`:""}`));
    lines.push("",`## ${t("Execution runbook","实施步骤")}`);p.runbook.forEach(x=>{lines.push(`### ${x.order}. ${x.title}`);if(x.instruction)lines.push(x.instruction);if(x.command)lines.push("```text",x.command,"```");if(x.configuration)lines.push("```text",x.configuration,"```");if(x.successCriteria)lines.push(`${t("Success criteria","成功标准")}: ${x.successCriteria}`);if(x.triggers?.length)lines.push(`${t("Rollback triggers","回退触发条件")}: ${x.triggers.join(", ")}`);lines.push("");});
    lines.push(`## ${t("Minimal forward configuration","最小前向配置")}`,"```text",p.forward.configuration||t("No configuration changes required.","无需配置变更。"),"```","",`## ${t("Rollback configuration","回退配置")}`,"```text",p.rollback.configuration||t("No rollback configuration required.","无需回退配置。"),"```");
    if(evaluation){lines.push("",`## ${t("Post-change decision","变更后判定")}`,`- ${t("Decision","判定")}: ${evaluation.decision}`,`- ${t("Passed","通过")}: ${evaluation.passed}`,`- ${t("Failed","失败")}: ${evaluation.failed}`,`- ${t("Inconclusive","证据不足")}: ${evaluation.inconclusive}`);if(evaluation.rollbackTriggers.length)lines.push(`- ${t("Rollback triggers","回退触发器")}: ${evaluation.rollbackTriggers.join(", ")}`);}
    lines.push("",`> ${t("Generated locally by NetEngineerLab. Review against the applicable vendor guide and your organization's change process before production execution.","由 NetEngineerLab 在本地生成。生产实施前请结合适用厂商文档及本单位变更流程复核。")}`);return lines.join("\n");}
  function renderMopDocument(p,evaluation){const md=mopMarkdown(p,evaluation);$("mopPreview").textContent=md;$("mopDocument").dataset.markdown=md;$("mopActions").hidden=false;}
  function updateVerificationProgress(){const boxes=[...verify.querySelectorAll("textarea[data-check]")],filled=boxes.filter(x=>x.value.trim()).length,total=boxes.length,el=$("verificationProgress");if(!el)return;el.classList.toggle("complete",total>0&&filled===total);el.classList.toggle("partial",filled>0&&filled<total);el.textContent=t(`${filled} of ${total} checks have evidence.`, `当前 ${filled} / ${total} 项检查已有证据。`);}

  function renderPlan(p){current=p;lastEvaluation=null;status.innerHTML=`${badge(p.status)} <strong>${esc(p.desired.logical)}</strong> · ${t("Risk","风险")} ${p.risk.score}/100 (${esc(p.risk.band)})`;renderRisk(p);explainPlan(p);const s=p.reconciliation.semantic;diff.innerHTML=`<div><b>${t("Members added","成员新增")}</b><code>${esc(s.members.added.join(", ")||"—")}</code></div><div><b>${t("Members removed","成员移除")}</b><code>${esc(s.members.removed.join(", ")||"—")}</code></div><div><b>${t("VLANs added","VLAN新增")}</b><code>${esc(s.vlans.added.join(", ")||"—")}</code></div><div><b>${t("VLANs removed","VLAN移除")}</b><code>${esc(s.vlans.removed.join(", ")||"—")}</code></div><div><b>Native/PVID</b><code>${esc(String(s.native.before))} → ${esc(String(s.native.after))}</code></div><div><b>Description</b><code>${esc(s.description.before||"—")} → ${esc(s.description.after||"—")}</code></div>`;forward.textContent=p.forward.configuration||t("No configuration changes required.","无需配置变更。");rollback.textContent=p.rollback.configuration||t("No rollback configuration required.","无需回退配置。");runbook.innerHTML=p.runbook.map(x=>`<li><span>${x.order}</span><div><b>${esc(x.title)}</b>${x.command?`<code>${esc(x.command)}</code>`:""}${x.configuration?`<pre>${esc(x.configuration)}</pre>`:""}${x.successCriteria?`<p><strong>${t("Success","成功标准")}:</strong> ${esc(x.successCriteria)}</p>`:""}${x.instruction?`<p>${esc(x.instruction)}</p>`:""}</div></li>`).join("");verify.innerHTML=p.verification.post.map(x=>`<label><span>${esc(x.command)}</span><small>${esc(x.expectation)}</small><textarea data-check="${x.id}" rows="4" placeholder="${t("Paste the real device output for this command","粘贴该命令的真实设备输出")}"></textarea></label>`).join("");$("verifyBtn").disabled=p.status!=="ready";$("resultDecision").innerHTML="";verify.querySelectorAll("textarea[data-check]").forEach(box=>box.addEventListener("input",updateVerificationProgress));updateVerificationProgress();const next=$("nextAction");if(next){if(p.status==="blocked")next.innerHTML=`<b>${t("Stop:","停止：")}</b> ${t("Resolve the blocking conflict before reviewing an execution runbook.","先解决阻断性冲突，不要进入实施步骤。")}`;else if(p.status==="noop")next.innerHTML=`<b>${t("No change required:","无需变更：")}</b> ${t("The managed state already matches the desired intent.","当前受管状态已与目标意图一致。")}`;else next.innerHTML=`<b>${t("Next:","下一步：")}</b> ${t("Review risk, forward config and rollback first; then follow the runbook and paste post-check evidence.","先审查风险、前向配置和回退配置；确认后按 Runbook 执行，并粘贴 Post-check 证据。")}`;}renderMopDocument(p,null);document.body.classList.add("has-plan");$("step2")?.classList.add("complete");$("step3").classList.add("complete");if(window.matchMedia("(max-width: 920px)").matches)document.querySelector(".result-card")?.scrollIntoView({behavior:"smooth",block:"start"});}
  $("planBtn").addEventListener("click",()=>{try{renderPlan(E.build(input()));$("plannerStatus").scrollIntoView({behavior:"smooth",block:"center"});}catch(e){current=null;status.innerHTML=`${badge("blocked")} ${esc(e.message)}`;$("resultExplanation").innerHTML=`<p><span>!</span>${esc(t("Fix the highlighted input or current-state conflict, then rebuild the plan.","请修正输入或当前状态冲突后重新生成计划。"))}</p>`;}});
  $("verifyBtn").addEventListener("click",()=>{if(!current)return;const out={};verify.querySelectorAll("textarea[data-check]").forEach(t=>out[t.dataset.check]=t.value);const r=E.evaluate(current,out);lastEvaluation=r;$("resultDecision").innerHTML=`${badge(r.decision.toLowerCase())}<strong>${esc(r.decision)}</strong><span>${t("Passed","通过")} ${r.passed} · ${t("Failed","失败")} ${r.failed} · ${t("Inconclusive","不确定")} ${r.inconclusive}</span>${r.rollbackTriggers.length?`<p>${t("Rollback triggers","回退触发器")}: ${esc(r.rollbackTriggers.join(", "))}</p>`:""}`;renderMopDocument(current,r);$("step4").classList.add("complete");const next=$("nextAction");if(next)next.innerHTML=`<b>${t("Verification decision:","验证结论：")}</b> ${esc(r.decision)}${r.rollbackTriggers.length?` · ${t("Review rollback triggers before the next action.","执行下一步前请先检查回退触发条件。")}`:""}`;});
  $("sampleBtn").addEventListener("click",()=>{syncDevice(true);$("scenarioNote").textContent=t("Vendor sample loaded. Adjust the desired intent, then build the plan.","已载入厂商示例。请调整目标意图后生成变更计划。");});
  $("copyForward").addEventListener("click",()=>navigator.clipboard?.writeText(forward.textContent));$("copyRollback").addEventListener("click",()=>navigator.clipboard?.writeText(rollback.textContent));
  $("copyMop").addEventListener("click",()=>{if(current)navigator.clipboard?.writeText(mopMarkdown(current,lastEvaluation));});
  $("downloadMop").addEventListener("click",()=>{if(!current)return;const blob=new Blob([mopMarkdown(current,lastEvaluation)],{type:"text/markdown;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`NetEngineerLab-${current.desired.logical}-MOP.md`;document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove();});
  $("printMop").addEventListener("click",()=>{if(!current)return;document.body.classList.add("print-mop");window.print();setTimeout(()=>document.body.classList.remove("print-mop"),300);});
  syncDevice(true);applyScenario("cisco-stack-vlan");updateInputChecklist();
})();
