/**
 * NetEngineerLab
 * Version: V2.1-Phase2-FlagshipV1
 * Modified: 2026-09-05 17:28:00
 * Purpose: Browser-facing Network Change Planner & MOP Generator engine.
 * Scope: managed LAG + trunk/VLAN domain, aligned with Shared Core contracts.
 */
(function(root,factory){const api=factory();if(typeof module!=="undefined"&&module.exports)module.exports=api;else root.NELNetworkChangePlanner=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
const DEVICES={
 "cisco-c9200l-24t-4g":{vendor:"cisco-ios",label:"Cisco C9200L-24T-4G",memberMax:8,memberDefault:1,portStart:1,portEnd:4,resolve:(m,p)=>`GigabitEthernet${m}/1/${p}`,logical:id=>`Port-channel${id}`},
 "huawei-s5735-l24t4s-a1":{vendor:"huawei-vrp",label:"Huawei S5735-L24T4S-A1",memberMax:1,memberDefault:1,portStart:25,portEnd:28,resolve:(m,p)=>`GigabitEthernet0/0/${p}`,logical:id=>`Eth-Trunk${id}`},
 "h3c-s5130s-28p-ei":{vendor:"h3c-comware",label:"H3C S5130S-28P-EI",memberMax:1,memberDefault:1,portStart:25,portEnd:28,resolve:(m,p)=>`GigabitEthernet${m}/0/${p}`,logical:id=>`Bridge-Aggregation${id}`},
 "juniper-ex3400-24t":{vendor:"juniper-junos",label:"Juniper EX3400-24T",memberMax:10,memberDefault:0,portStart:0,portEnd:23,resolve:(m,p)=>`ge-${m}/0/${p}`,logical:id=>`ae${id}`},
 "arista-7050sx3-48yc8":{vendor:"arista-eos",label:"Arista 7050SX3-48YC8",memberMax:1,memberDefault:1,portStart:49,portEnd:56,resolve:(m,p)=>`Ethernet${p}`,logical:id=>`Port-Channel${id}`}
};
function uniq(a){return [...new Set(a)]}
function ints(v){return uniq(String(v||"").split(/[\s,]+/).filter(Boolean).map(Number).filter(n=>Number.isInteger(n)&&n>=1&&n<=4094)).sort((a,b)=>a-b)}
function setDiff(a,b){const A=new Set(a||[]),B=new Set(b||[]);return {added:[...B].filter(x=>!A.has(x)),removed:[...A].filter(x=>!B.has(x)),unchanged:[...B].filter(x=>A.has(x))}}
function normalizeDesired(input){const d=DEVICES[input.deviceId];if(!d)throw Error("unknown_device");const id=Number(input.aggregateId);if(!Number.isInteger(id)||id<1||id>4096)throw Error("invalid_aggregate_id");const allowed=ints(input.allowedVlans);if(!allowed.length)throw Error("allowed_vlans_required");const native=input.nativeVlan==null||input.nativeVlan===""?null:Number(input.nativeVlan);if(native!=null&&!allowed.includes(native))throw Error("native_vlan_must_be_allowed");const members=(input.members||[]).map((x,i)=>{const m=x.member==null||x.member===""?d.memberDefault:Number(x.member),p=Number(x.port);if(!Number.isInteger(m)||m<0||m>d.memberMax)throw Error(`member_${i+1}_out_of_range`);if(!Number.isInteger(p)||p<d.portStart||p>d.portEnd)throw Error(`port_${i+1}_out_of_range`);return d.resolve(m,p)});if(members.length<2)throw Error("at_least_two_members_required");if(uniq(members).length!==members.length)throw Error("duplicate_member_interface");return {deviceId:input.deviceId,vendor:d.vendor,aggregateId:id,logical:d.logical(id),lagMode:input.lagMode==="static"?"static":"lacp",members:uniq(members),allowedVlans:allowed,nativeVlan:native,description:String(input.description||"").trim()};}
function parseCiscoLike(text,vendor){const s=String(text||"").replace(/\r/g,"");const lines=s.split("\n"),aggregates=[],trunks=[],bindings=[],vlans=[];let cur=null;for(const raw of lines){const line=raw.trim();let m=line.match(/^vlan\s+(\d+)/i);if(m){vlans.push(Number(m[1]));continue}m=line.match(/^interface\s+(Port-?[Cc]hannel|Port-Channel)(\d+)/i);if(m){cur={kind:"agg",id:Number(m[2]),name:m[1]+m[2],members:[],mode:"lacp",allowedVlans:[],nativeVlan:null,description:null};aggregates.push(cur);trunks.push(cur);continue}m=line.match(/^interface\s+(.+)/i);if(m){cur={kind:"phy",name:m[1]};continue}if(!cur)continue;m=line.match(/^description\s+(.+)/i);if(m&&cur.kind==="agg")cur.description=m[1].trim();m=line.match(/^channel-group\s+(\d+)\s+mode\s+(\S+)/i);if(m&&cur.kind==="phy"){bindings.push({interfaceName:cur.name,aggregateId:Number(m[1])});let a=aggregates.find(x=>x.id===Number(m[1]));if(a&&!a.members.includes(cur.name))a.members.push(cur.name);if(a)a.mode=/active|passive/i.test(m[2])?"lacp":"static";}m=line.match(/^switchport trunk allowed vlan(?: add)?\s+(.+)/i);if(m&&cur.kind==="agg")cur.allowedVlans=ints(m[1]);m=line.match(/^switchport trunk native vlan\s+(\d+)/i);if(m&&cur.kind==="agg")cur.nativeVlan=Number(m[1]);}
for(const a of aggregates)a.members=uniq(bindings.filter(b=>b.aggregateId===a.id).map(b=>b.interfaceName));for(const a of aggregates)a.members=uniq(bindings.filter(b=>b.aggregateId===a.id).map(b=>b.interfaceName));for(const a of aggregates)a.members=uniq(bindings.filter(b=>b.aggregateId===a.id).map(b=>b.interfaceName));return {aggregates:aggregates.map(a=>({id:a.id,name:a.name,mode:a.mode,members:a.members,description:a.description})),interfaceVlans:trunks.map(a=>({name:a.name,mode:"trunk",allowedVlans:a.allowedVlans,nativeVlan:a.nativeVlan,description:a.description})),memberBindings:bindings,knownVlans:uniq(vlans).sort((a,b)=>a-b)};}
function parseHuawei(text){const s=String(text||"").replace(/\r/g,"");const lines=s.split("\n"),aggregates=[],trunks=[],bindings=[],vlans=[];let cur=null;for(const raw of lines){const line=raw.trim();let m=line.match(/^vlan\s+(\d+)/i);if(m){vlans.push(Number(m[1]));continue}m=line.match(/^interface\s+Eth-Trunk(\d+)/i);if(m){cur={kind:"agg",id:Number(m[1]),name:`Eth-Trunk${m[1]}`,mode:"lacp",members:[],allowedVlans:[],nativeVlan:null,description:null};aggregates.push(cur);trunks.push(cur);continue}m=line.match(/^interface\s+(.+)/i);if(m){cur={kind:"phy",name:m[1]};continue}if(!cur)continue;m=line.match(/^description\s+(.+)/i);if(m&&cur.kind==="agg")cur.description=m[1].trim();m=line.match(/^eth-trunk\s+(\d+)/i);if(m&&cur.kind==="phy"){bindings.push({interfaceName:cur.name,aggregateId:Number(m[1])});let a=aggregates.find(x=>x.id===Number(m[1]));if(a)a.members.push(cur.name)}if(/mode lacp/i.test(line)&&cur.kind==="agg")cur.mode="lacp";m=line.match(/^port trunk allow-pass vlan\s+(.+)/i);if(m&&cur.kind==="agg")cur.allowedVlans=ints(m[1]);m=line.match(/^port trunk pvid vlan\s+(\d+)/i);if(m&&cur.kind==="agg")cur.nativeVlan=Number(m[1]);}
return {aggregates:aggregates.map(a=>({id:a.id,name:a.name,mode:a.mode,members:a.members,description:a.description})),interfaceVlans:trunks.map(a=>({name:a.name,mode:"trunk",allowedVlans:a.allowedVlans,nativeVlan:a.nativeVlan,description:a.description})),memberBindings:bindings,knownVlans:uniq(vlans).sort((a,b)=>a-b)};}
function parseH3C(text){const s=String(text||"").replace(/\r/g,"");const lines=s.split("\n"),aggregates=[],trunks=[],bindings=[],vlans=[];let cur=null;for(const raw of lines){const line=raw.trim();let m=line.match(/^vlan\s+(\d+)/i);if(m){vlans.push(Number(m[1]));continue}m=line.match(/^interface\s+Bridge-Aggregation(\d+)/i);if(m){cur={kind:"agg",id:Number(m[1]),name:`Bridge-Aggregation${m[1]}`,mode:"lacp",members:[],allowedVlans:[],nativeVlan:null,description:null};aggregates.push(cur);trunks.push(cur);continue}m=line.match(/^interface\s+(.+)/i);if(m){cur={kind:"phy",name:m[1]};continue}if(!cur)continue;m=line.match(/^description\s+(.+)/i);if(m&&cur.kind==="agg")cur.description=m[1].trim();m=line.match(/^port link-aggregation group\s+(\d+)/i);if(m&&cur.kind==="phy"){bindings.push({interfaceName:cur.name,aggregateId:Number(m[1])});let a=aggregates.find(x=>x.id===Number(m[1]));if(a)a.members.push(cur.name)}if(/link-aggregation mode dynamic/i.test(line)&&cur.kind==="agg")cur.mode="lacp";m=line.match(/^port trunk permit vlan\s+(.+)/i);if(m&&cur.kind==="agg")cur.allowedVlans=ints(m[1]);m=line.match(/^port trunk pvid vlan\s+(\d+)/i);if(m&&cur.kind==="agg")cur.nativeVlan=Number(m[1]);}
return {aggregates:aggregates.map(a=>({id:a.id,name:a.name,mode:a.mode,members:a.members,description:a.description})),interfaceVlans:trunks.map(a=>({name:a.name,mode:"trunk",allowedVlans:a.allowedVlans,nativeVlan:a.nativeVlan,description:a.description})),memberBindings:bindings,knownVlans:uniq(vlans).sort((a,b)=>a-b)};}
function parseJunos(text){const s=String(text||"").replace(/\r/g,"");const aggregates=[],trunks=[],bindings=[],vlans=[];for(const line of s.split("\n").map(x=>x.trim())){let m=line.match(/^set interfaces (\S+) ether-options 802\.3ad ae(\d+)/);if(m)bindings.push({interfaceName:m[1],aggregateId:Number(m[2])});m=line.match(/^set interfaces ae(\d+) aggregated-ether-options lacp/);if(m&&!aggregates.some(x=>x.id===Number(m[1])))aggregates.push({id:Number(m[1]),name:`ae${m[1]}`,mode:"lacp",members:[],description:null});m=line.match(/^set interfaces ae(\d+) description "?(.+?)"?$/);if(m){let a=aggregates.find(x=>x.id===Number(m[1]))||{id:Number(m[1]),name:`ae${m[1]}`,mode:"lacp",members:[],description:null};if(!aggregates.includes(a))aggregates.push(a);a.description=m[2].replace(/^"|"$/g,"")}m=line.match(/^set interfaces ae(\d+) unit 0 family ethernet-switching interface-mode trunk/);if(m&&!trunks.some(x=>x.name===`ae${m[1]}`))trunks.push({name:`ae${m[1]}`,mode:"trunk",allowedVlans:[],nativeVlan:null,description:null});m=line.match(/^set interfaces ae(\d+) native-vlan-id (\d+)/);if(m){let t=trunks.find(x=>x.name===`ae${m[1]}`)||{name:`ae${m[1]}`,mode:"trunk",allowedVlans:[],nativeVlan:null,description:null};if(!trunks.includes(t))trunks.push(t);t.nativeVlan=Number(m[2])}m=line.match(/^set interfaces ae(\d+) unit 0 family ethernet-switching vlan members \[ (.+) \]/);if(m){let t=trunks.find(x=>x.name===`ae${m[1]}`)||{name:`ae${m[1]}`,mode:"trunk",allowedVlans:[],nativeVlan:null,description:null};if(!trunks.includes(t))trunks.push(t);t.allowedVlans=ints(m[2])}m=line.match(/^set vlans \S+ vlan-id (\d+)/);if(m)vlans.push(Number(m[1]));}
for(const a of aggregates)a.members=bindings.filter(b=>b.aggregateId===a.id).map(b=>b.interfaceName);for(const t of trunks){const a=aggregates.find(a=>a.name===t.name);if(a)t.description=a.description}return {aggregates,interfaceVlans:trunks,memberBindings:bindings,knownVlans:uniq(vlans).sort((a,b)=>a-b)};}
function parseRunning(vendor,text){let state;if(vendor==="cisco-ios"||vendor==="arista-eos")state=parseCiscoLike(text,vendor);else if(vendor==="huawei-vrp")state=parseHuawei(text);else if(vendor==="h3c-comware")state=parseH3C(text);else state=parseJunos(text);const managedLines=state.aggregates.length+state.interfaceVlans.length+state.memberBindings.length;return {...state,opaqueLines:String(text||"").split(/\r?\n/).filter(x=>x.trim()).slice(managedLines),safe:true};}
function reconcile(snapshot,d){const agg=snapshot.aggregates.find(x=>x.id===d.aggregateId)||null,trunk=snapshot.interfaceVlans.find(x=>x.name.toLowerCase()===d.logical.toLowerCase())||null;const currentMembers=agg?agg.members:[],currentVlans=trunk?trunk.allowedVlans:[];const conflicts=[];for(const b of snapshot.memberBindings)if(d.members.includes(b.interfaceName)&&b.aggregateId!==d.aggregateId)conflicts.push({code:"MEMBER_BOUND_TO_OTHER_AGGREGATE",severity:"error",interfaceName:b.interfaceName,aggregateId:b.aggregateId});if(snapshot.knownVlans.length)for(const v of d.allowedVlans)if(!snapshot.knownVlans.includes(v))conflicts.push({code:"VLAN_NOT_PRESENT",severity:"error",vlan:v});const semantic={members:setDiff(currentMembers,d.members),vlans:setDiff(currentVlans,d.allowedVlans),native:{before:trunk?trunk.nativeVlan:null,after:d.nativeVlan,changed:(trunk?trunk.nativeVlan:null)!==d.nativeVlan},description:{before:(trunk&&trunk.description)||(agg&&agg.description)||null,after:d.description||null,changed:((trunk&&trunk.description)||(agg&&agg.description)||null)!==(d.description||null)},aggregateExists:!!agg,trunkExists:!!trunk,mode:{before:agg?agg.mode:null,after:d.lagMode,changed:!agg||agg.mode!==d.lagMode}};const drift=!agg||!trunk||semantic.members.added.length||semantic.members.removed.length||semantic.vlans.added.length||semantic.vlans.removed.length||semantic.native.changed||semantic.description.changed||semantic.mode.changed;return {status:conflicts.length?"blocked":drift?"drift":"in-sync",aggregate:agg,trunk,semantic,conflicts};}
function cmds(d,rec){const v=d.vendor,add=[],undo=[];const push=(f,r)=>{if(f)add.push(f);if(r)undo.unshift(r)};const L=d.logical,id=d.aggregateId;function bind(iface,on){if(v==="cisco-ios"||v==="arista-eos")return `interface ${iface}\n ${on?`channel-group ${id} mode ${d.lagMode==="lacp"?"active":"on"}`:`no channel-group ${id}`}`;if(v==="huawei-vrp")return `interface ${iface}\n ${on?`eth-trunk ${id}`:`undo eth-trunk`}`;if(v==="h3c-comware")return `interface ${iface}\n ${on?`port link-aggregation group ${id}`:`undo port link-aggregation group`}`;return `${on?"set":"delete"} interfaces ${iface} ether-options 802.3ad ae${id}`;}
if(!rec.aggregate){if(v==="cisco-ios"||v==="arista-eos")push(`interface ${L}`,`no interface ${L}`);else if(v==="huawei-vrp")push(`interface ${L}${d.lagMode==="lacp"?"\n mode lacp-static":""}`,`undo interface ${L}`);else if(v==="h3c-comware")push(`interface ${L}${d.lagMode==="lacp"?"\n link-aggregation mode dynamic":""}`,`undo interface ${L}`);else push(`${d.lagMode==="lacp"?`set interfaces ${L} aggregated-ether-options lacp active`:""}`,`delete interfaces ${L}`);}
for(const x of rec.semantic.members.added)push(bind(x,true),bind(x,false));for(const x of rec.semantic.members.removed)push(bind(x,false),bind(x,true));
if(v==="cisco-ios"||v==="arista-eos"){if(!rec.trunk)push(`interface ${L}\n switchport mode trunk`,``);if(rec.semantic.vlans.added.length||rec.semantic.vlans.removed.length)push(`interface ${L}\n switchport trunk allowed vlan ${d.allowedVlans.join(",")}`,rec.trunk?`interface ${L}\n switchport trunk allowed vlan ${(rec.trunk.allowedVlans||[]).join(",")}`:`interface ${L}\n no switchport trunk allowed vlan`);if(rec.semantic.native.changed)push(`interface ${L}\n ${d.nativeVlan!=null?`switchport trunk native vlan ${d.nativeVlan}`:"no switchport trunk native vlan"}`,rec.trunk&&rec.trunk.nativeVlan!=null?`interface ${L}\n switchport trunk native vlan ${rec.trunk.nativeVlan}`:`interface ${L}\n no switchport trunk native vlan`);if(rec.semantic.description.changed)push(`interface ${L}\n ${d.description?`description ${d.description}`:"no description"}`,rec.semantic.description.before?`interface ${L}\n description ${rec.semantic.description.before}`:`interface ${L}\n no description`);}
else if(v==="huawei-vrp"){if(!rec.trunk)push(`interface ${L}\n port link-type trunk`,``);if(rec.semantic.vlans.added.length||rec.semantic.vlans.removed.length)push(`interface ${L}\n port trunk allow-pass vlan ${d.allowedVlans.join(" ")}`,rec.trunk?`interface ${L}\n undo port trunk allow-pass vlan all\n port trunk allow-pass vlan ${(rec.trunk.allowedVlans||[]).join(" ")}`:`interface ${L}\n undo port trunk allow-pass vlan all`);if(rec.semantic.native.changed)push(`interface ${L}\n ${d.nativeVlan!=null?`port trunk pvid vlan ${d.nativeVlan}`:"undo port trunk pvid vlan"}`,rec.trunk&&rec.trunk.nativeVlan!=null?`interface ${L}\n port trunk pvid vlan ${rec.trunk.nativeVlan}`:`interface ${L}\n undo port trunk pvid vlan`);}
else if(v==="h3c-comware"){if(!rec.trunk)push(`interface ${L}\n port link-type trunk`,``);if(rec.semantic.vlans.added.length||rec.semantic.vlans.removed.length)push(`interface ${L}\n port trunk permit vlan ${d.allowedVlans.join(" ")}`,rec.trunk?`interface ${L}\n undo port trunk permit vlan all\n port trunk permit vlan ${(rec.trunk.allowedVlans||[]).join(" ")}`:`interface ${L}\n undo port trunk permit vlan all`);if(rec.semantic.native.changed)push(`interface ${L}\n ${d.nativeVlan!=null?`port trunk pvid vlan ${d.nativeVlan}`:"undo port trunk pvid vlan"}`,rec.trunk&&rec.trunk.nativeVlan!=null?`interface ${L}\n port trunk pvid vlan ${rec.trunk.nativeVlan}`:`interface ${L}\n undo port trunk pvid vlan`);}
else {if(!rec.trunk)push(`set interfaces ${L} unit 0 family ethernet-switching interface-mode trunk`,``);if(rec.semantic.vlans.added.length||rec.semantic.vlans.removed.length)push(`set interfaces ${L} unit 0 family ethernet-switching vlan members [ ${d.allowedVlans.join(" ")} ]`,rec.trunk?`set interfaces ${L} unit 0 family ethernet-switching vlan members [ ${(rec.trunk.allowedVlans||[]).join(" ")} ]`:`delete interfaces ${L} unit 0 family ethernet-switching vlan`);if(rec.semantic.native.changed)push(d.nativeVlan!=null?`set interfaces ${L} native-vlan-id ${d.nativeVlan}`:`delete interfaces ${L} native-vlan-id`,rec.trunk&&rec.trunk.nativeVlan!=null?`set interfaces ${L} native-vlan-id ${rec.trunk.nativeVlan}`:`delete interfaces ${L} native-vlan-id`);}
return {forward:add.filter(Boolean).join("\n\n"),rollback:undo.filter(Boolean).join("\n\n")};}
function risk(rec,snapshot){if(rec.status==="blocked")return {score:100,band:"critical",factors:[{code:"BLOCKED_CONFLICT",points:100}]};let s=0,f=[];const add=(p,c)=>{if(p){s+=p;f.push({code:c,points:p})}};if(!rec.aggregate)add(12,"NEW_AGGREGATE");add(rec.semantic.members.added.length*8,"MEMBERS_ADDED");add(rec.semantic.members.removed.length*12,"MEMBERS_REMOVED");add(rec.semantic.vlans.removed.length?Math.min(18,6+rec.semantic.vlans.removed.length*3):0,"VLANS_REMOVED");add(rec.semantic.vlans.added.length?Math.min(8,2+rec.semantic.vlans.added.length):0,"VLANS_ADDED");if(rec.semantic.native.changed)add(16,"NATIVE_VLAN_CHANGE");if(rec.semantic.description.changed)add(1,"DESCRIPTION_CHANGE");if(snapshot.opaqueLines.length)add(Math.min(10,Math.ceil(snapshot.opaqueLines.length/20)),"OPAQUE_CONTEXT");s=Math.min(100,s);return {score:s,band:s>=75?"critical":s>=50?"high":s>=25?"medium":"low",factors:f,requiresPeerReview:s>=50,requiresMaintenanceWindow:s>=50};}
function verification(d){const L=d.logical,first=d.members[0],v=d.vendor;let c;if(v==="cisco-ios")c={aggregate:"show etherchannel summary",detail:`show interfaces ${L}`,trunk:"show interfaces trunk",vlan:"show vlan brief"};else if(v==="arista-eos")c={aggregate:"show port-channel dense",detail:`show interfaces ${L}`,trunk:`show interfaces ${L} trunk`,vlan:"show vlan"};else if(v==="huawei-vrp")c={aggregate:`display eth-trunk ${d.aggregateId}`,detail:`display interface ${L}`,trunk:`display port vlan ${L}`,vlan:"display vlan"};else if(v==="h3c-comware")c={aggregate:`display link-aggregation verbose bridge-aggregation ${d.aggregateId}`,detail:`display interface ${L}`,trunk:"display port trunk",vlan:"display vlan"};else c={aggregate:`show interfaces ${L} extensive`,detail:`show interfaces ${L} terse`,trunk:`show ethernet-switching interface ${L}`,vlan:"show vlans"};return {post:[{id:"post-aggregate-up",command:c.aggregate,expectation:`${L} up with ${d.members.length} intended members`},{id:"post-logical-up",command:c.detail,expectation:`${L} operational/up with no new errors`},{id:"post-trunk-state",command:c.trunk,expectation:`Allowed VLANs ${d.allowedVlans.join(",")}${d.nativeVlan!=null?`; native/PVID ${d.nativeVlan}`:""}`},{id:"post-vlan-inventory",command:c.vlan,expectation:"Target VLANs remain present"}],pre:[{id:"pre-aggregate-state",command:c.aggregate,expectation:"Capture current aggregate/member state"},{id:"pre-logical-state",command:c.detail,expectation:`Capture ${L} state`},{id:"pre-trunk-state",command:c.trunk,expectation:"Capture trunk state"},{id:"pre-vlan-inventory",command:c.vlan,expectation:"Confirm target VLAN inventory"}],rollbackTriggers:["AGGREGATE_DOWN","MEMBER_COUNT_MISMATCH","TRUNK_SEMANTIC_MISMATCH","UNEXPECTED_MEMBER","NEW_INTERFACE_ERRORS"]};}
function runbook(status,riskObj,verify,delta){const steps=[];let n=1;const p=(kind,title,payload={})=>steps.push({order:n++,kind,title,...payload});p("control","Change authorization",{instruction:riskObj.requiresPeerReview?"Obtain peer review/change approval":"Standard operator approval"});for(const x of verify.pre)p("precheck",x.id,{command:x.command,successCriteria:x.expectation});if(status==="noop")p("decision","No change required",{instruction:"Current managed state already matches desired intent."});else if(status==="blocked")p("decision","Change blocked",{instruction:"Resolve blocking conflicts before execution."});else{p("execute","Apply minimal forward delta",{configuration:delta.forward});for(const x of verify.post)p("postcheck",x.id,{command:x.command,successCriteria:x.expectation});p("decision","Rollback gate",{triggers:verify.rollbackTriggers});p("rollback","Rollback configuration",{configuration:delta.rollback});}return steps;}
function build(input){const d=normalizeDesired(input),snapshot=parseRunning(d.vendor,input.runningConfig),rec=reconcile(snapshot,d),delta=rec.status==="blocked"?{forward:"",rollback:""}:rec.status==="in-sync"?{forward:"",rollback:""}:cmds(d,rec),riskObj=risk(rec,snapshot),verify=verification(d),status=rec.status==="blocked"?"blocked":rec.status==="in-sync"?"noop":"ready";return {version:"1.0.0",status,desired:d,snapshot,reconciliation:rec,risk:riskObj,verification:verify,runbook:runbook(status,riskObj,verify,delta),forward:{configuration:delta.forward},rollback:{configuration:delta.rollback}};}
function numList(s){return ints(s)}
function evaluate(plan,outputs){if(!plan||!plan.desired)throw Error("plan_required");const d=plan.desired,o=outputs||{},results=[];function add(id,status,reason,trigger){results.push({id,status,reason,trigger})}const agg=String(o["post-aggregate-up"]||"");if(!agg.trim())add("post-aggregate-up","inconclusive","missing_output");else{let up=false,count=0;if(d.vendor==="cisco-ios"||d.vendor==="arista-eos"){up=new RegExp(`(?:Po|Port-?[Cc]hannel)${d.aggregateId}[^\\n]*(?:U|up)`,`i`).test(agg);count=d.members.filter(m=>agg.toLowerCase().includes(m.toLowerCase())||agg.toLowerCase().includes(m.replace(/^GigabitEthernet/i,"Gi").toLowerCase())||agg.toLowerCase().includes(m.replace(/^Ethernet/i,"Et").toLowerCase())).length;}else if(d.vendor==="huawei-vrp"){up=/operat(?:e|ing) status\s*:\s*up/i.test(agg);let m=agg.match(/Number Of Up Ports In Trunk\s*:\s*(\d+)/i);count=m?Number(m[1]):0;}else if(d.vendor==="h3c-comware"){up=/Bridge-Aggregation\d+/i.test(agg)&&!/down/i.test(agg);let m=agg.match(/Selected Ports?\s*:\s*(\d+)/i);count=m?Number(m[1]):d.members.filter(x=>agg.includes(x)).length;}else{up=new RegExp(`${d.logical}\\s+up\\s+up`,`i`).test(agg)||/Physical link is Up/i.test(agg);count=d.members.filter(x=>agg.includes(x)).length||d.members.length;}if(!up)add("post-aggregate-up","fail","aggregate_not_up","AGGREGATE_DOWN");else if(count&&count<d.members.length)add("post-aggregate-up","fail",`active_members_${count}_expected_${d.members.length}`,"MEMBER_COUNT_MISMATCH");else add("post-aggregate-up","pass");}
const logical=String(o["post-logical-up"]||"");if(!logical.trim())add("post-logical-up","inconclusive","missing_output");else if(/down|administratively down/i.test(logical)&&!/0 input errors/i.test(logical))add("post-logical-up","fail","logical_interface_not_up","AGGREGATE_DOWN");else{const errs=[...logical.matchAll(/(\d+)\s+(?:input |output |crc )?errors?/ig)].reduce((a,m)=>a+Number(m[1]),0);errs?add("post-logical-up","fail",`errors_${errs}`,"NEW_INTERFACE_ERRORS"):add("post-logical-up","pass");}
const trunk=String(o["post-trunk-state"]||"");if(!trunk.trim())add("post-trunk-state","inconclusive","missing_output");else{const found=numList(trunk).filter(x=>d.allowedVlans.includes(x));const same=JSON.stringify(uniq(found).sort((a,b)=>a-b))===JSON.stringify(d.allowedVlans);const nativeOk=d.nativeVlan==null||new RegExp(`(?:native|pvid|default vlan|native-vlan-id)\\D+${d.nativeVlan}\\b`,`i`).test(trunk);same&&nativeOk?add("post-trunk-state","pass"):add("post-trunk-state","fail","trunk_semantic_mismatch","TRUNK_SEMANTIC_MISMATCH");}
const vlan=String(o["post-vlan-inventory"]||"");if(!vlan.trim())add("post-vlan-inventory","inconclusive","missing_output");else{const found=numList(vlan).filter(x=>d.allowedVlans.includes(x));JSON.stringify(uniq(found).sort((a,b)=>a-b))===JSON.stringify(d.allowedVlans)?add("post-vlan-inventory","pass"):add("post-vlan-inventory","fail","target_vlan_inventory_incomplete");}
const failed=results.filter(x=>x.status==="fail"),inc=results.filter(x=>x.status==="inconclusive"),triggers=uniq(failed.map(x=>x.trigger).filter(Boolean));const decision=failed.length?(triggers.length?"ROLLBACK_REQUIRED":"FAIL"):inc.length?"INCONCLUSIVE":"PASS";return {decision,status:decision.toLowerCase(),results,rollbackTriggers:triggers,passed:results.filter(x=>x.status==="pass").length,failed:failed.length,inconclusive:inc.length};}
const samples={
 "cisco-ios":`vlan 10\nvlan 20\nvlan 30\nvlan 99\nvlan 100\ninterface GigabitEthernet1/1/1\n channel-group 10 mode active\ninterface GigabitEthernet2/1/1\n channel-group 10 mode active\ninterface Port-channel10\n description CORE-UPLINK-OLD\n switchport mode trunk\n switchport trunk allowed vlan 10,20,30,99\n switchport trunk native vlan 99`,
 "huawei-vrp":`vlan 10\nvlan 20\nvlan 30\nvlan 99\nvlan 100\ninterface GigabitEthernet0/0/25\n eth-trunk 10\ninterface GigabitEthernet0/0/26\n eth-trunk 10\ninterface Eth-Trunk10\n description CORE-UPLINK-OLD\n mode lacp-static\n port link-type trunk\n port trunk allow-pass vlan 10 20 30 99\n port trunk pvid vlan 99`,
 "h3c-comware":`vlan 10\nvlan 20\nvlan 30\nvlan 99\nvlan 100\ninterface GigabitEthernet1/0/25\n port link-aggregation group 10\ninterface GigabitEthernet1/0/26\n port link-aggregation group 10\ninterface Bridge-Aggregation10\n description CORE-UPLINK-OLD\n link-aggregation mode dynamic\n port link-type trunk\n port trunk permit vlan 10 20 30 99\n port trunk pvid vlan 99`,
 "juniper-junos":`set vlans V10 vlan-id 10\nset vlans V20 vlan-id 20\nset vlans V30 vlan-id 30\nset vlans V99 vlan-id 99\nset vlans V100 vlan-id 100\nset interfaces ge-0/0/0 ether-options 802.3ad ae10\nset interfaces ge-1/0/0 ether-options 802.3ad ae10\nset interfaces ae10 aggregated-ether-options lacp active\nset interfaces ae10 description CORE-UPLINK-OLD\nset interfaces ae10 unit 0 family ethernet-switching interface-mode trunk\nset interfaces ae10 unit 0 family ethernet-switching vlan members [ 10 20 30 99 ]\nset interfaces ae10 native-vlan-id 99`,
 "arista-eos":`vlan 10\nvlan 20\nvlan 30\nvlan 99\nvlan 100\ninterface Ethernet49\n channel-group 10 mode active\ninterface Ethernet50\n channel-group 10 mode active\ninterface Port-Channel10\n description CORE-UPLINK-OLD\n switchport mode trunk\n switchport trunk allowed vlan 10,20,30,99\n switchport trunk native vlan 99`
};
return Object.freeze({DEVICES,normalizeDesired,parseRunning,reconcile,build,evaluate,samples});});
