(function(){
  "use strict";
  const zh=(document.documentElement.lang||"").toLowerCase().startsWith("zh"), $=id=>document.getElementById(id), E=window.NELSfpQsfpEngine;
  const labels=zh?{PASS:"通过",WARNING:"需要确认",FAIL:"不兼容",rate:"速率",lanes:"通道",media:"介质",fiber:"光纤",wavelength:"波长",connector:"接口",input:"输入有效性",powerRange:"光功率范围",sensitivity:"接收灵敏度",overload:"接收过载",redundancy:"冗余与备件",condition:"环境与DOM",ok:"光预算通过；投产前请核对厂商编码、固件、FEC和DOM。",copied:"已复制",csv:"已导出"}:{PASS:"Compatible",WARNING:"Verify host support",FAIL:"Not compatible",rate:"Rate",lanes:"Lanes",media:"Media",fiber:"Fiber",wavelength:"Wavelength",connector:"Connector",input:"Input validity",powerRange:"Optical power range",sensitivity:"Receiver sensitivity",overload:"Receiver overload",redundancy:"Redundancy and spares",condition:"Environment and DOM",ok:"Optical budget passes; confirm vendor coding, firmware, FEC and DOM before deployment.",copied:"Copied",csv:"Exported"};
  const presets={"10glr":{form:"SFP+",rate:10,lanes:1,media:"SMF",wave:1310,connector:"LC",tx:-8.2,txMax:.5,rx:-14.4,overload:.5,fiber:"SMF",distance:10,attenuation:.35,connectors:2,connectorLoss:.3,splices:2,spliceLoss:.1,margin:1.5},"25glr":{form:"SFP28",rate:25,lanes:1,media:"SMF",wave:1310,connector:"LC",tx:-7,txMax:2,rx:-13.3,overload:.5,fiber:"SMF",distance:10,attenuation:.35,connectors:2,connectorLoss:.3,splices:2,spliceLoss:.1,margin:2},"100glr4":{form:"QSFP28",rate:100,lanes:4,media:"SMF",wave:1310,connector:"LC",tx:-4.3,txMax:4.5,rx:-10.6,overload:4.5,fiber:"SMF",distance:10,attenuation:.35,connectors:2,connectorLoss:.3,splices:2,spliceLoss:.1,margin:2},"40gsr4":{form:"QSFP+",rate:40,lanes:4,media:"MMF",wave:850,connector:"MPO",tx:-7.6,txMax:2.4,rx:-9.5,overload:2.4,fiber:"MMF",distance:.15,attenuation:3,connectors:2,connectorLoss:.35,splices:0,spliceLoss:.1,margin:.5}};
  Object.keys(E.FORM_FACTORS).forEach(v=>["aForm","bForm"].forEach(id=>$(id)&&$(id).add(new Option(v,v))));
  const val=id=>$(id)?$(id).value:undefined;
  function setPreset(){const p=presets[val("preset")]||presets["10glr"];[["a",p],["b",p]].forEach(([x,q])=>{[[x+"Form",q.form],[x+"Rate",q.rate],[x+"Lanes",q.lanes],[x+"Media",q.media],[x+"Wave",q.wave],[x+"Connector",q.connector],[x+"Tx",q.tx],[x+"TxMax",q.txMax],[x+"Rx",q.rx],[x+"Overload",q.overload]].forEach(([id,v])=>{if($(id))$(id).value=v;});});[["fiber",p.fiber],["distance",p.distance],["attenuation",p.attenuation],["connectors",p.connectors],["connectorLoss",p.connectorLoss],["splices",p.splices],["spliceLoss",p.spliceLoss],["margin",p.margin]].forEach(([id,v])=>{if($(id))$(id).value=v;});calculate(false);}
  function mod(x){return{formFactor:val(x+"Form"),aggregateRateGbps:val(x+"Rate"),lanes:val(x+"Lanes"),media:val(x+"Media"),wavelengthNm:val(x+"Wave"),connector:val(x+"Connector"),txMinDbm:val(x+"Tx"),txMaxDbm:val(x+"TxMax"),rxSensitivityDbm:val(x+"Rx"),rxOverloadDbm:val(x+"Overload"),domHealthPct:val(x+"Dom")};}
  function values(){const out={moduleA:mod("a"),moduleB:mod("b"),link:{fiberType:val("fiber"),connector:val("aConnector"),distanceKm:val("distance"),attenuationDbPerKm:val("attenuation"),connectorCount:val("connectors"),connectorLossDb:val("connectorLoss"),spliceCount:val("splices"),spliceLossDb:val("spliceLoss"),engineeringMarginDb:val("margin")},scenario:{agingYears:val("agingYears"),temperatureDeltaC:val("tempDelta"),maintenanceLossDb:val("maintenanceLoss")}};if($("pathCount")||$("spareModules"))out.redundancy={pathCount:val("pathCount")||1,spareModules:val("spareModules")||0,dualPath:true};return out;}
  let last; const db=v=>Number.isFinite(v)?v.toFixed(2)+" dB":"—";
  function calculate(track){last=E.calculate(values());if($("rxPower"))$("rxPower").textContent=Number.isFinite(last.budget.estimatedRxDbm)?last.budget.estimatedRxDbm.toFixed(2)+" dBm":"—";[[$("loss"),last.budget.physicalLossDb],[$("sensitivity"),last.budget.sensitivityMarginDb],[$("design"),last.budget.designMarginDb],[$("overload"),last.budget.overloadHeadroomDb]].forEach(([e,v])=>{if(e)e.textContent=db(v);});if($("status")){ $("status").className="status "+last.status.toLowerCase();$("status").textContent=labels[last.status];}if($("checks"))$("checks").innerHTML=last.checks.map(c=>`<article class="${c.pass?"pass":"fail"}"><span>${c.pass?"✓":"×"}</span><div><strong>${labels[c.id]||c.id}</strong><small>${c.detail}</small></div></article>`).join("");if($("advice"))$("advice").textContent=last.warnings.length?last.warnings.join(" · "):labels.ok;if(track&&window.nelTrack)window.nelTrack("sfp_qsfp_compatibility_check",{status:last.status});}
  function report(){if(!last)calculate(false);return[`NetEngineerLab ${zh?"光模块兼容性工程报告":"SFP/QSFP compatibility engineering report"}`,`${zh?"状态":"Status"}: ${labels[last.status]}`,`Estimated Rx: ${$("rxPower")?.textContent}`,`Physical loss: ${$("loss")?.textContent}`,`Design margin: ${$("design")?.textContent}`,`Condition loss: ${db(last.budget.conditionLossDb)}`,...last.checks.map(c=>`${c.pass?"PASS":"FAIL"} ${labels[c.id]||c.id}: ${c.detail}`)].join("\n");}
  async function copy(){try{await navigator.clipboard.writeText(report());}catch(e){}if($("copy"))$("copy").textContent=labels.copied;}
  function csv(){const a=document.createElement("a"),b=new Blob(["\uFEFFResult\n"+report().split("\n").map(x=>`"${x.replaceAll('"','""')}"`).join("\n")],{type:"text/csv"});a.href=URL.createObjectURL(b);a.download="sfp-qsfp-compatibility-report.csv";a.click();if($("csv"))$("csv").textContent=labels.csv;}
  document.querySelectorAll("input,select").forEach(e=>e.addEventListener("input",()=>calculate(false)));if($("preset"))$("preset").addEventListener("change",setPreset);if($("calculate"))$("calculate").addEventListener("click",()=>calculate(true));if($("copy"))$("copy").addEventListener("click",copy);if($("csv"))$("csv").addEventListener("click",csv);setPreset();
})();
