(()=>{'use strict';
const zh=document.documentElement.lang.startsWith('zh'),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const T=zh?{pass:'通过',warning:'警告',fail:'失败',inconclusive:'无法判定',recommended:'推荐方案',saved:'草稿已保存到本机',loaded:'已载入本机草稿',quote:'仅用于规划，不是采购报价。',multi:'多缆组合',datasheet:'设备收发参数必须按厂商规格书复核。',custom:'自定义',bom:['PON 端口','一级 / 二级 / 三级分光器','ONU 数量','馈线光缆','配线光缆','ODF 端口 / 盘片','接续盘']}:{pass:'PASS',warning:'WARNING',fail:'FAIL',inconclusive:'INCONCLUSIVE',recommended:'Recommended plan',saved:'Draft saved locally',loaded:'Local draft loaded',quote:'Planning only; not a procurement quotation.',multi:'Multiple-cable combination',datasheet:'Verify all transceiver values against vendor datasheets.',custom:'Custom',bom:['PON ports','Level 1 / 2 / 3 splitters','ONU count','Feeder cable','Distribution cable','ODF ports / trays','Splice trays']};
const profiles={bplus:{maxOdnLoss:28,maxReachKm:20},cplus:{maxOdnLoss:32,maxReachKm:20},n1:{maxOdnLoss:29,maxReachKm:20},n2:{maxOdnLoss:31,maxReachKm:20},custom:{maxOdnLoss:'',maxReachKm:''}};
const defaults=[
 {id:'A',name:zh?'方案 A':'Plan A',profile:'cplus',distanceKm:10,downAttenuation:.25,upAttenuation:.35,splitterLoss:17,spliceCount:10,spliceLoss:.1,connectorCount:4,connectorLoss:.3,otherLoss:.3,agingAllowance:1,temperatureAllowance:.5,maintenanceAllowance:1,repairAllowance:.5,pathPenalty:0,downTxMin:4,downTxMax:6,downRxSensitivity:-28,downRxOverload:-8,upTxMin:1,upTxMax:4,upRxSensitivity:-31,upRxOverload:-8,maxOdnLoss:32,maxReachKm:20},
 {id:'B',name:zh?'方案 B':'Plan B',profile:'bplus',distanceKm:10,downAttenuation:.25,upAttenuation:.35,splitterLoss:17,spliceCount:10,spliceLoss:.1,connectorCount:4,connectorLoss:.3,otherLoss:.3,agingAllowance:1,temperatureAllowance:.5,maintenanceAllowance:1,repairAllowance:.5,pathPenalty:0,downTxMin:4,downTxMax:6,downRxSensitivity:-28,downRxOverload:-8,upTxMin:1,upTxMax:4,upRxSensitivity:-31,upRxOverload:-8,maxOdnLoss:20,maxReachKm:20},
 {id:'C',name:zh?'方案 C':'Plan C',profile:'custom',distanceKm:10,downAttenuation:.25,upAttenuation:.35,splitterLoss:17,spliceCount:10,spliceLoss:.1,connectorCount:4,connectorLoss:.3,otherLoss:.3,agingAllowance:1,temperatureAllowance:.5,maintenanceAllowance:1,repairAllowance:.5,pathPenalty:0,downTxMin:4,downTxMax:'',downRxSensitivity:-28,downRxOverload:-8,upTxMin:1,upTxMax:4,upRxSensitivity:-31,upRxOverload:-8,maxOdnLoss:32,maxReachKm:20}
];
const labels=zh?{profile:'技术档案',distanceKm:'距离 km',downAttenuation:'下行衰减 dB/km',upAttenuation:'上行衰减 dB/km',splitterLoss:'总分光损耗 dB',spliceCount:'熔接数量',spliceLoss:'单熔接损耗 dB',connectorCount:'连接器数量',connectorLoss:'单连接器损耗 dB',otherLoss:'其他损耗 dB',agingAllowance:'老化预留 dB',temperatureAllowance:'温度预留 dB',maintenanceAllowance:'维护预留 dB',repairAllowance:'修复预留 dB',pathPenalty:'光学代价 dB',maxOdnLoss:'最大 ODN 损耗 dB',maxReachKm:'系统距离 km',downTxMin:'下行 Tx min dBm',downTxMax:'下行 Tx max dBm',downRxSensitivity:'下行 Rx 灵敏度 dBm',downRxOverload:'下行 Rx 过载 dBm',upTxMin:'上行 Tx min dBm',upTxMax:'上行 Tx max dBm',upRxSensitivity:'上行 Rx 灵敏度 dBm',upRxOverload:'上行 Rx 过载 dBm'}:{profile:'Technical profile',distanceKm:'Distance km',downAttenuation:'Down attenuation dB/km',upAttenuation:'Up attenuation dB/km',splitterLoss:'Total splitter loss dB',spliceCount:'Splice count',spliceLoss:'Loss / splice dB',connectorCount:'Connector count',connectorLoss:'Loss / connector dB',otherLoss:'Other loss dB',agingAllowance:'Aging allowance dB',temperatureAllowance:'Temperature allowance dB',maintenanceAllowance:'Maintenance allowance dB',repairAllowance:'Repair allowance dB',pathPenalty:'Path penalty dB',maxOdnLoss:'Maximum ODN loss dB',maxReachKm:'System reach km',downTxMin:'Down Tx min dBm',downTxMax:'Down Tx max dBm',downRxSensitivity:'Down Rx sensitivity dBm',downRxOverload:'Down Rx overload dBm',upTxMin:'Up Tx min dBm',upTxMax:'Up Tx max dBm',upRxSensitivity:'Up Rx sensitivity dBm',upRxOverload:'Up Rx overload dBm'};
defaults.forEach((x,i)=>Object.assign(x,{stages:i===2?3:2,r1:i===1?4:8,r2:i===2?4:8,r3:i===2?4:1,operatorCap:i===1?32:64,protectionFactor:1,reservePct:20,existingOdfPorts:12}));
Object.assign(labels,zh?{stages:'分光级数',r1:'一级比例 1:',r2:'二级比例 1:',r3:'三级比例 1:',operatorCap:'单端口运营上限',protectionFactor:'保护系数 1/2',reservePct:'预留率 %',existingOdfPorts:'现有 ODF 端口'}:{stages:'Splitter stages',r1:'Level 1 ratio 1:',r2:'Level 2 ratio 1:',r3:'Level 3 ratio 1:',operatorCap:'Operator cap / port',protectionFactor:'Protection factor 1/2',reservePct:'Reserve rate %',existingOdfPorts:'Existing ODF ports'});
const keys=Object.keys(labels).filter(k=>k!=='profile');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function addPlan(data){const el=document.createElement('details');el.className='plan';el.open=data.id==='A';el.dataset.id=data.id;el.innerHTML=`<summary><strong>${esc(data.name)}</strong><span class="plan-status">—</span></summary><div class="plan-grid"><label>${labels.profile}<select data-key="profile"><option value="bplus">GPON B+</option><option value="cplus">GPON C+</option><option value="n1">XGS-PON N1</option><option value="n2">XGS-PON N2</option><option value="custom">${T.custom}</option></select></label>${keys.map(k=>`<label>${labels[k]}<input type="number" step="any" data-key="${k}" value="${esc(data[k])}"></label>`).join('')}</div><p class="plan-output"></p>`;el.querySelector('[data-key=profile]').value=data.profile||'custom';el.addEventListener('input',e=>{if(e.target.dataset.key==='profile'&&e.target.value!=='custom')Object.entries(profiles[e.target.value]).forEach(([k,v])=>el.querySelector(`[data-key=${k}]`).value=v);calculate()});$('#plans').append(el);}
function readPlan(el){const out={id:el.dataset.id,name:el.querySelector('summary strong').textContent};el.querySelectorAll('[data-key]').forEach(x=>out[x.dataset.key]=x.value);return out;}
const resourceIds=['targetOnu','stages','r1','r2','r3','operatorCap','protectionFactor','reservePct','maxCableCores','odfTrayCapacity','spliceTrayCapacity','existingOdfPorts','existingOdfTrays','existingSpliceTrays','existingFeederCores','existingDistributionCores'];
function collect(){const o={};resourceIds.forEach(id=>o[id]=$('#'+id).value);o.scenarios=$$('.plan').map(readPlan);return o;}
function statusText(s){return T[s.toLowerCase()]||s;}
function cableText(x){return `${x.cables.join(' + ')} (${x.provided})${x.multiCable?' · '+T.multi:''}`;}
function calculate(){const r=window.NELOdfOdnEngine.calculate(collect());window.lastOdfResult=r;const p=r.resources;$('#ponPorts').textContent=p.ponPorts;$('#capacity').textContent=p.servedCapacity;$('#effective').textContent=`1:${p.effectiveOnuPerPort}`;$('#splitters').textContent=`${p.splitterCounts.level1} / ${p.splitterCounts.level2} / ${p.splitterCounts.level3}`;$('#feeder').textContent=cableText(p.segments.feeder);$('#distribution').textContent=cableText(p.segments.distribution);$('#drop').textContent=cableText(p.segments.drop);$('#odfGap').textContent=`${p.gaps.odfPorts}`;$('#trayGap').textContent=`${p.gaps.odfTrays} / ${p.gaps.spliceTrays}`;$('#recommendation').textContent=r.recommended?`${T.recommended}: ${r.scenarios.find(x=>x.id===r.recommended).name}`:(zh?'没有可推荐的完整方案':'No conclusive plan can be recommended');r.scenarios.forEach((x,i)=>{const el=$$('.plan')[i];el.querySelector('.plan-status').textContent=statusText(x.status);el.querySelector('.plan-status').className=`plan-status s-${x.status.toLowerCase()}`;el.querySelector('.plan-output').textContent=`PON ${x.resources.ponPorts} · ${zh?'缺口':'gap'} ${x.resourceGap} · ${zh?'过建':'overbuild'} ${x.overbuild} · ${zh?'下行/上行设计损耗':'Down/Up design loss'} ${x.down.designLoss??'—'} / ${x.up.designLoss??'—'} dB · ${zh?'最小余量':'Minimum margin'} ${x.minMargin??'—'} dB${x.diagnostics.length?' · '+x.diagnostics.join(' · '):''}`;});const values=[p.ponPorts,`${p.splitterCounts.level1} / ${p.splitterCounts.level2} / ${p.splitterCounts.level3}`,p.targetOnu,cableText(p.segments.feeder),cableText(p.segments.distribution),`${p.odfPorts} / ${p.odfTrays}`,p.spliceTrays];$('#bomRows').innerHTML=T.bom.map((label,i)=>`<tr><th>${label}</th><td>${values[i]}</td></tr>`).join('');}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);}
function packageData(){return {canonical:window.lastOdfResult.metadata.canonical,source:location.href,reviewedAt:window.lastOdfResult.metadata.reviewedAt,input:collect(),result:window.lastOdfResult};}
$('#exportJson').onclick=()=>download('odf-odn-resource-plan.json',JSON.stringify(packageData(),null,2),'application/json');$('#exportCsv').onclick=()=>download('odf-odn-resource-plan.csv','\uFEFF'+window.NELOdfOdnEngine.toCSV(window.lastOdfResult,{source:location.href,input:collect()}),'text/csv;charset=utf-8');$('#printReport').onclick=()=>print();$('#saveDraft').onclick=()=>{localStorage.setItem('nel-odf-odn-draft',JSON.stringify({...packageData(),savedAt:new Date().toISOString()}));$('#feedback').textContent=T.saved};$('#loadDraft').onclick=()=>{const stored=JSON.parse(localStorage.getItem('nel-odf-odn-draft')||'null');if(!stored)return;const d=stored.input||stored;resourceIds.forEach(id=>{if(d[id]!==undefined)$('#'+id).value=d[id]});$('#plans').innerHTML='';(d.scenarios||defaults).forEach(addPlan);calculate();$('#feedback').textContent=T.loaded};
defaults.forEach(addPlan);resourceIds.forEach(id=>$('#'+id).addEventListener('input',calculate));calculate();
})();
