(function(){"use strict";var E=window.NELReportCenter;if(!E)return;var zh=window.NEL_LANG==="zh",tx=function(en,cn){return zh?cn:en;},$=function(id){return document.getElementById(id);},records=[];
function feedback(message,error){var el=$("feedback");el.textContent=message;el.classList.toggle("error",!!error);}
function update(){var body=$("records");body.replaceChildren();records.forEach(function(r,i){var tr=document.createElement("tr");[r.tool,r.status,r.generatedAt||"—",r.sourceUrl||"—"].forEach(function(v){var td=document.createElement("td");td.textContent=v;tr.appendChild(td);});var action=document.createElement("td"),button=document.createElement("button");button.type="button";button.textContent=tx("Remove","移除");button.addEventListener("click",function(){records.splice(i,1);update();});action.appendChild(button);tr.appendChild(action);body.appendChild(tr);});$("count").textContent=String(records.length);$("deliverables").hidden=records.length===0;}
function addData(source,name){var added=E.parseImport(source,name);records=records.concat(added);update();feedback(tx("Added "+added.length+" result(s).","已添加 "+added.length+" 条结果。"));}
$("importText").addEventListener("click",function(){try{addData($("sourceText").value,"pasted.json");$("sourceText").value="";}catch(e){feedback(e.message,true);}});
$("files").addEventListener("change",async function(event){var files=Array.from(event.target.files||[]);for(var file of files){try{addData(await file.text(),file.name);}catch(e){feedback(file.name+": "+e.message,true);}}event.target.value="";});
function bundle(){return E.createBundle(records,{project:$("project").value,owner:$("owner").value,locale:zh?"zh":"en",title:$("reportTitle").value});}
function download(name,content,type){var a=document.createElement("a"),url=URL.createObjectURL(new Blob([content],{type:type}));a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
$("exportReport").addEventListener("click",function(){try{download("engineering-report.md",E.toMarkdown(bundle(),"report"),"text/markdown;charset=utf-8");feedback(tx("Engineering report exported.","工程报告已导出。"));}catch(e){feedback(e.message,true);}});
[["exportMop","mop","engineering-mop.md"],["exportChecklist","checklist","engineering-checklist.md"],["exportLedger","ledger","engineering-results-register.md"]].forEach(function(item){$(item[0]).addEventListener("click",function(){try{download(item[2],E.toMarkdown(bundle(),item[1]),"text/markdown;charset=utf-8");feedback(tx("Deliverable exported.","交付文档已导出。"));}catch(e){feedback(e.message,true);}});});
$("exportJson").addEventListener("click",function(){try{download("engineering-results-bundle.json",JSON.stringify(bundle(),null,2),"application/json;charset=utf-8");feedback(tx("JSON bundle exported.","JSON 汇总包已导出。"));}catch(e){feedback(e.message,true);}});
$("exportCsv").addEventListener("click",function(){try{download("engineering-results-register.csv","\ufeff"+E.toCsv(bundle()),"text/csv;charset=utf-8");feedback(tx("CSV register exported.","CSV 台账已导出。"));}catch(e){feedback(e.message,true);}});
$("print").addEventListener("click",function(){try{var preview=$("printDocument");preview.textContent=E.toMarkdown(bundle(),"report");document.body.classList.add("print-report");window.print();setTimeout(function(){document.body.classList.remove("print-report");},500);}catch(e){feedback(e.message,true);}});
$("sample").addEventListener("click",function(){addData(JSON.stringify({results:[{tool:"Network Capacity Forecast Planner",website:"/tools/network-capacity-forecast-planner/",status:"WARNING",inputs:{capacityGbps:100,utilizationPct:68,annualGrowthPct:20},result:{monthsToThreshold:4,requiredCapacityGbps:126,additionalCapacityGbps:26}},{tool:"Network Risk Assessment",status:"REVIEW",result:{riskLevel:"MEDIUM",recommendation:"Confirm redundant path and maintenance window"}}]}),"sample.json");});
$("clear").addEventListener("click",function(){records=[];update();feedback(tx("Workspace cleared.","工作区已清空。"));});update();})();
