(()=>{'use strict';
const zh=document.documentElement.lang.startsWith('zh'),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const L=zh?{normal:'正常',abnormal:'异常',na:'不适用',unverified:'未核验',safe:'已核验，无未关闭异常',critical:'存在关键隐患',action:'需要整改',verify:'仍有未核验项',empty:'请至少添加一个检查项',copied:'报告已复制',saved:'草稿已保存在本机',loaded:'已载入本机草稿',site:'网站地址'}:{normal:'Normal',abnormal:'Abnormal',na:'N/A',unverified:'Unverified',safe:'Verified: no open abnormal item',critical:'Critical hazard present',action:'Remediation required',verify:'Unverified items remain',empty:'Add at least one assessment item',copied:'Report copied',saved:'Draft saved locally',loaded:'Local draft loaded',site:'Website'};
const presets={
 environment:zh?['机房温湿度与漏水','消防通道与封堵']:['Room temperature, humidity and leaks','Fire access and penetrations'],
 power:zh?['配电保护与接地','裸露带电部件防护']:['Distribution protection and grounding','Exposed energized-part protection'],
 fiber:zh?['ODF 标签与弯曲半径','光纤连接器清洁度']:['ODF labels and bend radius','Fiber connector cleanliness'],
 ports:zh?['端口告警与错误计数','闲置端口与防尘措施']:['Port alarms and error counters','Unused ports and dust protection'],
 resilience:zh?['双路由与单点故障','监控告警与通知闭环']:['Path diversity and single points of failure','Monitoring, alerting and notification closure']
};
let seq=0;
function option(v,t){return `<option value="${v}">${t}</option>`}
function addItem(category='custom',title=''){
 const id=`hz-${Date.now()}-${++seq}`,critical=category==='power'&&/裸露|Exposed/.test(title);
 const row=document.createElement('article');row.className='hazard-item';row.dataset.id=id;row.innerHTML=`<div class="item-head"><div><span class="category">${category}</span><input class="title" value="${title}" aria-label="${zh?'检查项名称':'Assessment item name'}"></div><button class="remove" type="button">×</button></div><div class="item-grid">
 <label>${zh?'当前状态':'Before status'}<select class="status">${option('normal',L.normal)}${option('abnormal',L.abnormal)}${option('na',L.na)}${option('unverified',L.unverified)}</select></label>
 <label>${zh?'可能性 1–5':'Likelihood 1–5'}<input class="likelihood" type="number" min="1" max="5" value="3"></label><label>${zh?'影响 1–5':'Impact 1–5'}<input class="impact" type="number" min="1" max="5" value="3"></label>
 <label>${zh?'暴露范围 %':'Exposure %'}<input class="exposure" type="number" min="0" max="100" value="100"></label><label>${zh?'控制有效性 %':'Control effectiveness %'}<input class="control" type="number" min="0" max="100" value="0"></label><label>${zh?'判断确定性 %':'Assessment certainty %'}<input class="certainty" type="number" min="0" max="100" value="80"></label>
 <label>${zh?'整改后状态':'After status'}<select class="afterStatus">${option('unverified',L.unverified)}${option('normal',L.normal)}${option('abnormal',L.abnormal)}${option('na',L.na)}</select></label><label>${zh?'整改后可能性':'After likelihood'}<input class="afterLikelihood" type="number" min="1" max="5" value="1"></label><label>${zh?'整改后影响':'After impact'}<input class="afterImpact" type="number" min="1" max="5" value="2"></label>
 <label>${zh?'责任人':'Owner'}<input class="owner" type="text"></label><label>${zh?'期限':'Due date'}<input class="dueDate" type="date"></label><label>${zh?'复核日期':'Review date'}<input class="reviewDate" type="date"></label><label>${zh?'整改状态':'Remediation status'}<select class="remediationStatus">${option('open',zh?'待处理':'Open')}${option('in-progress',zh?'处理中':'In progress')}${option('closed',zh?'已关闭':'Closed')}</select></label>
 <label>${zh?'关键规则 ID（仅硬规则）':'Critical rule ID (hard rules only)'}<input class="ruleId" value="${critical?'ELEC-EXPOSED-01':''}"></label><label class="wide">${zh?'触发条件（必须可见）':'Visible trigger condition'}<input class="criticalTrigger" value="${critical?(zh?'发现可接触的带电导体或防护缺失':'Accessible energized conductor or missing guard'):''}"></label></div>`;
 row.querySelector('.status').value=title?'unverified':'unverified';row.querySelector('.remove').onclick=()=>{row.remove();calculate()};row.addEventListener('input',calculate);$('#items').append(row);calculate();
}
function value(row,c){return row.querySelector('.'+c)?.value??''}
function collect(){return $$('.hazard-item').map(row=>({id:row.dataset.id,category:row.querySelector('.category').textContent,title:value(row,'title'),status:value(row,'status'),likelihood:value(row,'likelihood'),impact:value(row,'impact'),exposurePct:value(row,'exposure'),controlEffectivenessPct:value(row,'control'),certaintyPct:value(row,'certainty'),afterStatus:value(row,'afterStatus'),afterLikelihood:value(row,'afterLikelihood'),afterImpact:value(row,'afterImpact'),afterExposurePct:value(row,'exposure'),afterControlEffectivenessPct:100,afterCertaintyPct:value(row,'certainty'),owner:value(row,'owner'),dueDate:value(row,'dueDate'),reviewDate:value(row,'reviewDate'),remediationStatus:value(row,'remediationStatus'),ruleId:value(row,'ruleId'),criticalTrigger:value(row,'criticalTrigger')}));}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function calculate(){const result=window.NELHazardEngine.calculate({items:collect()});window.lastHazardResult=result;$('#empty').hidden=result.ok;if(!result.ok)return;const map={safe:L.safe,critical:L.critical,'action-required':L.action,'needs-verification':L.verify};$('#overall').textContent=map[result.overall];$('#overall').dataset.state=result.overall;$('#completion').textContent=result.completionPct+'%';$('#openCount').textContent=result.counts.abnormal;$('#unknownCount').textContent=result.counts.unverified;$('#reduction').textContent=result.riskReductionPct+'%';$('#topRisks').innerHTML=result.topRisks.length?result.topRisks.map(x=>`<li><strong>${esc(x.title)}</strong><span>${x.before.level.toUpperCase()} · ${x.before.score}/100${x.before.ruleId?` · ${esc(x.before.ruleId)} · ${esc(x.before.trigger)}`:''}<br>${zh?'责任人':'Owner'}: ${esc(x.owner||'—')} · ${zh?'期限':'Due'}: ${esc(x.dueDate||'—')} · ${zh?'复核':'Review'}: ${esc(x.reviewDate||'—')}</span></li>`).join(''):`<li>${zh?'暂无异常项；未核验项仍不得判定安全。':'No abnormal item. Unverified items still cannot be declared safe.'}</li>`;}
function report(){const r=window.lastHazardResult,risks=r.topRisks.map((x,i)=>`${i+1}. ${x.title} | ${x.before.score}/100 | ${zh?'责任人':'Owner'} ${x.owner||'—'} | ${zh?'期限':'Due'} ${x.dueDate||'—'} | ${zh?'复核':'Review'} ${x.reviewDate||'—'}${x.before.ruleId?` | ${x.before.ruleId}: ${x.before.trigger}`:''}`).join('\n');return `${zh?'网络隐患评估报告':'Network Hidden-Hazard Assessment Report'}\n${L.site}: https://netengineerlab.com/tools/network-risk-hidden-hazard-assessment-generator/${zh?'zh/':''}\n${zh?'完成率':'Completion'}: ${r.completionPct}%\n${zh?'异常':'Abnormal'}: ${r.counts.abnormal}; ${zh?'未核验':'Unverified'}: ${r.counts.unverified}; ${zh?'关键':'Critical'}: ${r.counts.critical}\n${zh?'整改前/整改后风险':'Before/After risk'}: ${r.beforeTotal} / ${r.afterTotal}; ${zh?'风险降低':'Risk reduction'}: ${r.riskReductionPct}%\n\n${zh?'主要风险':'Top risks'}\n${risks||'—'}\n\n${zh?'边界：本工具用于可追溯的工程筛查，不自动证明法规或标准合规；适用性须由当地法规、现场条件和合格专业人员复核。':'Boundary: This tool supports traceable engineering screening and does not prove automatic compliance. Applicability must be reviewed against local law, site conditions and qualified professional judgment.'}`}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$$('[data-preset]').forEach(b=>b.onclick=()=>presets[b.dataset.preset].forEach(t=>addItem(b.dataset.preset,t)));$('#addCustom').onclick=()=>addItem();$('#copyReport').onclick=async()=>{await navigator.clipboard.writeText(report());$('#feedback').textContent=L.copied};$('#exportJson').onclick=()=>download('network-hazard-assessment.json',JSON.stringify({source:location.href,boundary:report().split('\n').pop(),result:window.lastHazardResult},null,2),'application/json');$('#exportCsv').onclick=()=>download('network-hazard-assessment.csv','\uFEFF'+window.NELHazardEngine.toCSV(window.lastHazardResult),'text/csv;charset=utf-8');$('#printReport').onclick=()=>print();$('#saveDraft').onclick=()=>{localStorage.setItem('nel-hazard-draft',JSON.stringify({source:location.href,savedAt:new Date().toISOString(),items:collect()}));$('#feedback').textContent=L.saved};$('#loadDraft').onclick=()=>{const stored=JSON.parse(localStorage.getItem('nel-hazard-draft')||'{"items":[]}'),a=Array.isArray(stored)?stored:(stored.items||[]);$('#items').innerHTML='';a.forEach(x=>{addItem(x.category,x.title);const row=$$('.hazard-item').at(-1);Object.entries(x).forEach(([k,v])=>{const m={exposurePct:'exposure',controlEffectivenessPct:'control',certaintyPct:'certainty'}[k]||k;const e=row.querySelector('.'+m);if(e)e.value=v})});$('#feedback').textContent=L.loaded;calculate()};
presets.environment.forEach(t=>addItem('environment',t));
})();
