(function(){"use strict";
const $=id=>document.getElementById(id), n=id=>Number($(id)?.value||0), fmt=(v,d=1)=>Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
const zh=(document.documentElement.lang||"").toLowerCase().startsWith("zh");
const riskZh={
 CONDUCTOR_AMPACITY:"导体载流量低于保守场景设计电流",
 VOLTAGE_DROP:"馈线估算压降超出规划范围",
 INTERRUPTING_RATING:"断路器分断能力低于预期故障电流",
 N1_CAPACITY:"N-1 电源容量无法承载保守场景负载",
 CONTINUOUS_LOADING:"断路器持续负载率超过 80%",
 DC_MARGIN:"直流支路持续电流余量不足",
 MISSING_FAULT_DATA:"尚未填写故障电流或分断能力"
};
function collect(){const b={loadKW:n("loadKW"),acVoltage:n("acV"),phase:$("phase")?.value,powerFactor:n("pf"),efficiencyPct:n("eff"),headroomPct:n("head"),deratingPct:n("der"),dcVoltage:n("dcV"),dcLoadA:n("dcA"),dcHeadroomPct:n("dcHead"),growthPct:n("growthPct")||20,conservativePct:n("conservativePct")||35,ambientC:n("ambientC")||30,altitudeM:n("altitudeM"),conductorAmpacityA:n("conductorA"),conductorLengthM:n("lengthM"),conductorAreaMm2:n("areaMm2"),faultCurrentKA:n("faultKA"),breakerInterruptKA:n("interruptKA"),sourceUnits:n("sourceUnits")||1,unitRatingA:n("unitRatingA")||0};return {...b,before:b,after:{...b,growthPct:0,conservativePct:0,sourceUnits:Math.max(2,b.sourceUnits)}};}
function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function run(){const r=window.NELACDCBreakerEngine.calculate(collect());if(!r.ok)return;[["acbase",r.baseA," A"],["acdesign",r.designA," A"],["breaker",r.suggestedBreakerA," A"],["kva",r.apparentKVA," kVA"],["dcd",r.dcDesignA," A"],["dcb",r.suggestedDCBreakerA||"—",r.suggestedDCBreakerA?" A":""]].forEach(([id,v,u])=>{if($(id))$(id).textContent=(typeof v==="number"?fmt(v):v)+u;});if($("warn"))$("warn").textContent=(r.risks||[]).map(x=>zh?(riskZh[x.code]||x.message):`${x.severity}: ${x.message}`).join(" ")||(zh?"该结果仅为规划候选值；请复核导体、压降、故障电流和选择性要求。":"Planning candidate only; verify conductor, voltage drop, fault and selectivity requirements.");let box=$("engineeringExtras");if(!box){box=document.createElement("section");box.id="engineeringExtras";box.className="content-section";document.querySelector(".result-panel")?.appendChild(box);}box.innerHTML=zh?`<h2>工程门禁与场景</h2><p>风险：<strong>${r.riskLevel}</strong>；N-1：<strong>${r.summary.n1Pass?"通过":"不通过"}</strong>；导体：<strong>${r.scenarios.conservative.conductorPass?"通过":"不通过"}</strong>；压降：<strong>${fmt(r.scenarios.conservative.dropPct,2)}%</strong></p><p>优化前 / 优化后设计电流：${fmt(r.beforeAfter.before.designA,1)} A → ${fmt(r.beforeAfter.after.designA,1)} A</p><button type="button" id="downloadJson" class="btn">下载 JSON 报告</button> <button type="button" id="downloadCsv" class="btn">下载 CSV 校核表</button>`:`<h2>Engineering gates &amp; scenarios</h2><p>Risk: <strong>${r.riskLevel}</strong>; N-1: <strong>${r.summary.n1Pass?"PASS":"FAIL"}</strong>; conductor: <strong>${r.scenarios.conservative.conductorPass?"PASS":"FAIL"}</strong>; voltage drop: <strong>${fmt(r.scenarios.conservative.dropPct,2)}%</strong></p><p>Before / After design current: ${fmt(r.beforeAfter.before.designA,1)} A → ${fmt(r.beforeAfter.after.designA,1)} A</p><button type="button" id="downloadJson" class="btn">Download JSON report</button> <button type="button" id="downloadCsv" class="btn">Download CSV check sheet</button>`;$("downloadJson").onclick=()=>download("acdc-breaker-report.json",JSON.stringify(r,null,2),"application/json");$("downloadCsv").onclick=()=>download("acdc-breaker-check.csv",r.exportCSV(),"text/csv");}
document.querySelectorAll("input,select").forEach(e=>e.addEventListener("input",run));$("calculate")?.addEventListener("click",run);run();})();
