(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.NELRectifierSizingEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION='3.0.0', URL='https://netengineerlab.com/tools/telecom-rectifier-dc-power-sizing/';
const fields={dcVoltage:[53.5,1,1000],loadCurrentA:[0,0,1e6],batteryChargeCurrentA:[0,0,1e6],moduleCurrentA:[50,.01,1e5],installedModules:[0,0,10000,true],redundancyModules:[1,0,2,true],headroomPct:[15,0,100],efficiencyPct:[94,1,100],acVoltage:[230,1,1000],powerFactor:[.95,.1,1],growthPct:[0,0,200],rechargePeakPct:[0,0,200],conservativePct:[10,0,100],ambientTempC:[25,-40,80],altitudeM:[0,0,8000],tempDeratePctPer10C:[2,0,100],altitudeDeratePctPer1000M:[1,0,100],targetUtilizationPct:[100,10,100],frameMaxModules:[0,0,10000,true],frameInstalledModules:[0,0,10000,true]};
const ceil=v=>Math.ceil(v), meets=(a,b)=>a+1e-9>=b;
function calculate(raw={}){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))return{ok:false,errors:['input-object'],warnings:[],engineVersion:VERSION};
 const inputs={},errors=[];
 for(const [key,[fallback,min,max,integer]] of Object.entries(fields)){const v=raw[key]===undefined?fallback:raw[key];const n=typeof v==='number'?v:typeof v==='string'&&v.trim()!==''?Number(v):NaN;if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))errors.push(key);else inputs[key]=n;}
 inputs.phase=raw.phase===undefined?'1p':raw.phase;if(!['1p','3p'].includes(inputs.phase))errors.push('phase');
 if(errors.length)return{ok:false,errors,warnings:[],engineVersion:VERSION};
 const i=inputs;if(i.loadCurrentA+i.batteryChargeCurrentA<=0)errors.push('loadCurrentA');
 if(i.frameMaxModules&&i.frameInstalledModules>i.frameMaxModules)errors.push('frameInstalledModules');
 if((i.frameMaxModules&&i.installedModules>i.frameMaxModules)||(i.frameInstalledModules&&i.installedModules>i.frameInstalledModules))errors.push('installedModules');
 const tempDeratePct=Math.max(0,(i.ambientTempC-25)/10)*i.tempDeratePctPer10C,altitudeDeratePct=i.altitudeM/1000*i.altitudeDeratePctPer1000M,deratePct=100-tempDeratePct-altitudeDeratePct;
 if(deratePct<=0)errors.push('environment-capacity');if(errors.length)return{ok:false,errors,warnings:[],engineVersion:VERSION};
 const effectiveModuleA=i.moduleCurrentA*deratePct/100,planningModuleA=effectiveModuleA*i.targetUtilizationPct/100;
 const grown=i.loadCurrentA*(1+i.growthPct/100),peak=i.batteryChargeCurrentA*(1+i.rechargePeakPct/100);
 function demand(name,load,charge,head){const requiredA=(load+charge)*(1+head/100);return{name,loadA:load,chargeA:charge,headroomPct:head,requiredA,activeModules:ceil(requiredA/planningModuleA),recommendedModules:ceil(requiredA/planningModuleA)+i.redundancyModules};}
 const demands=[demand('baseline',i.loadCurrentA,i.batteryChargeCurrentA,i.headroomPct),demand('growth',grown,i.batteryChargeCurrentA,i.headroomPct),demand('recharge-peak',i.loadCurrentA,peak,i.headroomPct),demand('growth-recharge',grown,peak,i.headroomPct),demand('conservative',grown,peak,i.headroomPct+i.conservativePct)];
 const worst=demands.reduce((a,b)=>a.requiredA>=b.requiredA?a:b),selected=i.installedModules||worst.recommendedModules;
 function assess(d,modules){const capacityA=modules*effectiveModuleA,n1CapacityA=Math.max(0,modules-1)*effectiveModuleA,n2CapacityA=Math.max(0,modules-2)*effectiveModuleA,risks=[];
 const s={...d,modules,capacityA,planningCapacityA:modules*planningModuleA,utilizationPct:capacityA?d.requiredA/capacityA*100:0,marginA:capacityA-d.requiredA,n1CapacityA,n2CapacityA,survivesNormal:meets(capacityA,d.requiredA),survives1:meets(n1CapacityA,d.requiredA),survives2:meets(n2CapacityA,d.requiredA),n1MarginA:n1CapacityA-d.requiredA,n2MarginA:n2CapacityA-d.requiredA,targetSurvives:meets(Math.max(0,modules-i.redundancyModules)*planningModuleA,d.requiredA)};
 if(!s.survivesNormal)risks.push('normal-capacity-fail');if(!s.survives1&&i.redundancyModules>=1)risks.push('N-1-fail');if(!s.survives2&&i.redundancyModules>=2)risks.push('N-2-fail');if(!s.targetSurvives)risks.push('target-reserve-shortfall');if(s.utilizationPct>i.targetUtilizationPct+1e-9)risks.push('high-utilization');if(i.installedModules&&modules<d.recommendedModules)risks.push('installed-under-sized');if(i.frameMaxModules&&modules>i.frameMaxModules)risks.push('frame-limit');if(i.frameInstalledModules&&modules>i.frameInstalledModules)risks.push('shelf-installed-limit');s.risks=risks;return s;}
 const scenarios=demands.map(d=>assess(d,selected)),worstSelected=scenarios.find(s=>s.name===worst.name),currentModules=i.installedModules||demands[0].recommendedModules;
 // A controller proposal never reduces communications load.
 const balancedChargeA=Math.min(peak,Math.max(0,Math.max(0,currentModules-i.redundancyModules)*planningModuleA/(1+(i.headroomPct+i.conservativePct)/100)-grown));
 const plans=[{...assess(worst,currentModules),name:'current',peakChargeA:peak},{...assess(demand('balanced',grown,balancedChargeA,i.headroomPct+i.conservativePct),currentModules),name:'balanced',peakChargeA:balancedChargeA,rechargeLimited:balancedChargeA<peak},{...assess(worst,Math.max(currentModules,worst.recommendedModules)),name:'expansion',peakChargeA:peak}];
 const risks=[...new Set([...scenarios,...plans].flatMap(s=>s.risks))],riskLevel=risks.some(x=>x.includes('fail')||x.includes('limit')||x==='installed-under-sized')?'HIGH':risks.length?'MEDIUM':'LOW';
 const power=s=>{const dcOutputKW=(s.loadA+s.chargeA)*i.dcVoltage/1000,acInputKW=dcOutputKW/(i.efficiencyPct/100);return{dcOutputKW,acInputKW,acInputA:acInputKW*1000/(i.acVoltage*i.powerFactor*(i.phase==='3p'?Math.sqrt(3):1))};};scenarios.forEach(s=>Object.assign(s,power(s)));plans.forEach(s=>Object.assign(s,power(s)));
 const expansion=plans[2],deliverables={currentModules,proposedModules:expansion.modules,additionalModules:Math.max(0,expansion.modules-currentModules),additionalSlots:i.frameInstalledModules?Math.max(0,expansion.modules-i.frameInstalledModules):null,frameFits:i.frameMaxModules?expansion.modules<=i.frameMaxModules:null,installedSlotsFit:i.frameInstalledModules?expansion.modules<=i.frameInstalledModules:null,rechargeLimitProposalA:balancedChargeA,rechargeLimitFeasible:plans[1].targetSurvives,verifiedFrameLimit:!!i.frameMaxModules,verifiedInstalledSlots:!!i.frameInstalledModules};
 const expansionA=Math.max(0,Math.max(0,selected-i.redundancyModules)*planningModuleA/(1+(i.headroomPct+i.conservativePct)/100)-grown-peak);
 return{ok:true,engineVersion:VERSION,inputs,dcVoltage:i.dcVoltage,loadCurrentA:i.loadCurrentA,batteryChargeCurrentA:i.batteryChargeCurrentA,moduleRatedA:i.moduleCurrentA,effectiveModuleA,planningModuleA,deratePct,tempDeratePct,altitudeDeratePct,requiredA:worst.requiredA,activeModules:worst.activeModules,recommendedModules:worst.recommendedModules,selectedModules:selected,normalCapacityA:worstSelected.capacityA,normalUtilPct:worstSelected.utilizationPct,after1CapacityA:worstSelected.n1CapacityA,after2CapacityA:worstSelected.n2CapacityA,survives1:worstSelected.survives1,survives2:worstSelected.survives2,marginA:worstSelected.marginA,expansionA,...power(worst),efficiencyPct:i.efficiencyPct,scenarios,plans,deliverables,worstScenario:worst.name,riskLevel,risks,warnings:risks};
}
function report(r,context={}){const language=context.language==='zh'?'zh':'en';return{toolName:language==='zh'?'通信开关电源与整流模块容量配置计算器':'Telecom Rectifier & DC Power System Sizing Calculator',generatedAt:context.generatedAt||new Date().toISOString(),language,website:URL+(language==='zh'?'zh/':''),engineVersion:VERSION,assumptions:language==='zh'?["直流电压采用正幅值；模块额定电流须适用于输入母线电压和交流电压。","线性温度及海拔降额系数是用户规划假设，不代表厂家曲线。","目标负载率仅应用一次于规划容量；故障校核使用环境降额物理容量。","交流估算包含运行负载及回充；工程余量表示直流储备，不代表实际消耗。","回充限流须核对电池恢复时间和控制器设置；不覆盖共用交流馈线、电池续航及共因故障。"]:["DC voltage is a positive magnitude; rated current must be valid at this bus voltage and AC input.","Linear temperature/altitude coefficients are user planning assumptions, not manufacturer curves.","Target utilization is applied once to planning capacity; failure checks use environmental physical capacity.","AC estimates include operating load and recharge; engineering headroom is DC reserve, not actual power consumption.","Recharge limiting requires battery recovery-time and controller review. Shared AC feeds, battery autonomy and common-mode faults are excluded."],inputs:r.inputs,results:r};}
function toJSON(r,context){return JSON.stringify(report(r,context),null,2);}
const ZH_LABELS={"engine_version":"引擎版本","dcVoltage":"直流母线电压_V","loadCurrentA":"通信负载_A","batteryChargeCurrentA":"回充电流_A","moduleCurrentA":"模块额定电流_A","installedModules":"现有模块数","redundancyModules":"冗余模块数","headroomPct":"工程余量_%","efficiencyPct":"整流效率_%","acVoltage":"交流电压_V","powerFactor":"功率因数","growthPct":"负载增长_%","rechargePeakPct":"回充增幅_%","conservativePct":"额外保守余量_百分点","ambientTempC":"环境温度_摄氏度","altitudeM":"海拔_m","tempDeratePctPer10C":"每10摄氏度降额_%","altitudeDeratePctPer1000M":"每1000米降额_%","targetUtilizationPct":"目标负载率_%","frameMaxModules":"机框最大模块数","frameInstalledModules":"已安装模块槽位","phase":"交流相制","1p":"单相","3p":"三相","currentModules":"当前模块数","proposedModules":"建议模块数","additionalModules":"新增模块数","additionalSlots":"新增槽位数","frameFits":"机框可行性","installedSlotsFit":"已安装槽位可行性","rechargeLimitProposalA":"限流建议_A","rechargeLimitFeasible":"限流可行性","verifiedFrameLimit":"机框限制已录入","verifiedInstalledSlots":"槽位限制已录入","baseline":"当前负载","growth":"负载增长","recharge-peak":"回充峰值","growth-recharge":"增长与回充叠加","conservative":"叠加工况与保守余量","current":"当前方案","balanced":"回充限流调整","expansion":"扩容方案","normal-capacity-fail":"正常容量不足","N-1-fail":"单模块故障容量不足","N-2-fail":"双模块故障容量不足","target-reserve-shortfall":"目标冗余不足","high-utilization":"超过目标负载率","installed-under-sized":"现有模块数低于建议","frame-limit":"超出机框容量","shelf-installed-limit":"需要新增槽位","scenario":"工况","plan":"方案","input":"输入","assumption":"模型假设","deliverable":"交付项","existing_modules":"现有模块","proposed_total_modules":"建议总模块","additional_modules":"新增模块","additional_slots":"新增槽位","frame_fits":"机框容量校核","recharge_limit_proposal_A":"回充限流建议_A","UNVERIFIED":"未校核","PASS":"通过","FAIL":"未通过","baseline design when installed=0":"现有数量为0时采用基线配置","growth + peak recharge + conservative reserve":"负载增长、回充峰值及保守余量叠加工况","verify model compatibility and DC/AC ratings":"核对模块兼容性及交流/直流额定值","0 slot input means unknown":"槽位输入0表示未知","frame replacement needed when false":"未通过时需要更大机框","controller and recovery-time review required":"须核对控制器及电池恢复时间","cannot meet load at target reserve":"目标冗余下无法承担通信负载"};
function csv(rows,zh=false){return rows.map(row=>row.map(v=>'"'+String(zh?(v===null?'未校核':typeof v==='boolean'?(v?'是':'否'):(ZH_LABELS[v]??v)):(v??'UNVERIFIED')).replace(/"/g,'""')+'"').join(',')).join('\n');}
function toCSV(r,context){const p=report(r,context),zh=p.language==='zh',rows=[[zh?'工具名称':'tool_name',p.toolName],[zh?'生成时间':'generated_at',p.generatedAt],[zh?'语言':'language',p.language],[zh?'网站地址':'website',p.website],['engine_version',VERSION]];Object.entries(p.inputs||{}).forEach(([k,v])=>rows.push(['input',k,v]));p.assumptions.forEach(a=>rows.push(['assumption',a]));rows.push(zh?['类型','场景/方案','所需电流_A','模块数','环境容量_A','目标容量_A','负载率_%','正常','N-1','N-2','目标冗余','N-1余量_A','N-2余量_A','风险']:['type','scenario/plan','required_A','modules','physical_capacity_A','planning_capacity_A','utilization_pct','normal','N-1','N-2','target_reserve','N-1_margin_A','N-2_margin_A','risks']);for(const [type,list] of [['scenario',r.scenarios||[]],['plan',r.plans||[]]])list.forEach(s=>rows.push([type,s.name,s.requiredA,s.modules,s.capacityA,s.planningCapacityA,s.utilizationPct,s.survivesNormal?'PASS':'FAIL',s.survives1?'PASS':'FAIL',s.survives2?'PASS':'FAIL',s.targetSurvives?'PASS':'FAIL',s.n1MarginA,s.n2MarginA,s.risks.map(k=>zh?(ZH_LABELS[k]||k):k).join('|')]));Object.entries(r.deliverables||{}).forEach(([k,v])=>rows.push(['deliverable',k,v]));return csv(rows,zh);}
function toBOM(r,context){const p=report(r,context),zh=p.language==='zh',d=r.deliverables;return toCSV(r,context)+'\n'+csv([[zh?'工具名称':'tool_name',p.toolName],[zh?'生成时间':'generated_at',p.generatedAt],[zh?'语言':'language',p.language],[zh?'网站地址':'website',p.website],zh?['规划清单','数量/值','校核说明']:['planning_item','quantity/value','check'],['existing_modules',d.currentModules,'baseline design when installed=0'],['proposed_total_modules',d.proposedModules,'growth + peak recharge + conservative reserve'],['additional_modules',d.additionalModules,'verify model compatibility and DC/AC ratings'],['additional_slots',d.additionalSlots??'UNVERIFIED','0 slot input means unknown'],['frame_fits',d.frameFits??'UNVERIFIED','frame replacement needed when false'],['recharge_limit_proposal_A',d.rechargeLimitProposalA,d.rechargeLimitFeasible?'controller and recovery-time review required':'cannot meet load at target reserve']],zh);}
return{VERSION,calculate,report,toJSON,toCSV,toBOM};});
