const $=id=>document.getElementById(id);const L=document.documentElement.lang.startsWith('en')?'en':'zh';
const TXT={zh:{healthy:'✓ 健康',warning:'⚠ 风险',failed:'✕ 超限',invalid:'请检查输入：数量必须为非负整数，距离和损耗必须为有效非负数，最大发送功率不得低于最小发送功率，过载门限必须高于灵敏度。',ok:'标准ODN预算充足，最小/最大发送功率对应的接收窗口均满足限制。',warn:'链路可用，但工程余量或接收窗口余量偏小，请核对发送功率范围、分光级数和老化余量。',fail:'链路预算超限，或最不利接收功率低于灵敏度/高于过载门限，请检查收发器规格、分光器级联、距离、接头污染和弯曲损耗。',copied:'结果已复制',saved:'记录已保存',downloaded:'CSV 已导出',empty:'暂无记录。完成计算后点击“保存记录”。',clear:'确定清空全部记录吗？'},en:{healthy:'✓ Healthy',warning:'⚠ Caution',failed:'✕ Failed',invalid:'Check the inputs. Counts must be non-negative integers; distance and losses must be finite and non-negative; maximum transmit power must not be below minimum; overload must be above sensitivity.',ok:'The standard ODN budget is sufficient and the receive-power window for minimum/maximum transmit power meets both limits.',warn:'The link is usable but engineering or receiver-window margin is limited. Verify the transmit-power range, splitter stages and ageing allowance.',fail:'The design exceeds the budget, or a worst-case receive power is below sensitivity / above overload. Check transceiver specifications, splitter cascade, distance, contamination and bending loss.',copied:'Result copied',saved:'Record saved',downloaded:'CSV exported',empty:'No saved records yet. Calculate and click “Save record”.',clear:'Clear all saved records?'}};
const A={'1310':.35,'1490':.30,'1550':.20,'1625':.25};const P={custom:null,'gpon-b':{tx:1.5,txMax:5,sens:-27,over:-8,penalty:.5,m:3,w:'1490',d:10,s1:'10.5',s2:'10.5'},'gpon-c':{tx:3,txMax:7,sens:-30,over:-8,penalty:1,m:3,w:'1490',d:10,s1:'10.5',s2:'10.5'},epon:{tx:2,txMax:7,sens:-27,over:-3,penalty:.5,m:3,w:'1490',d:10,s1:'10.5',s2:'10.5'},datacenter:{tx:-1,txMax:0,sens:-7,over:0,penalty:0,m:1.5,w:'1310',d:.5,s1:'0',s2:'0'}};let last=null;
function num(id){return parseFloat($(id).value)}function set(id,v){$(id).textContent=Number(v).toFixed(2)}
function valid(){return ['distance','attenuation','spliceCount','spliceLoss','connectorCount','connectorLoss','splitter1','splitter2','splitter3','otherLoss','opticalPenalty','engineeringMargin'].every(id=>Number.isFinite(num(id))&&num(id)>=0)&&['txPower','rxSensitivity','rxOverload'].every(id=>Number.isFinite(num(id)))}
function setAtt(){const w=$('wavelength').value;if(A[w]!=null){$('attenuation').value=A[w].toFixed(2);$('attenuation').readOnly=true}else $('attenuation').readOnly=false}
function preset(){const p=P[$('preset').value];if(!p)return;$('txPower').value=p.tx;$('txMaxPower').value=p.txMax;$('rxSensitivity').value=p.sens;$('rxOverload').value=p.over;$('opticalPenalty').value=p.penalty;$('engineeringMargin').value=p.m;$('wavelength').value=p.w;$('distance').value=p.d;$('splitter1').value=p.s1;$('splitter2').value=p.s2||'0';$('splitter3').value='0';setAtt();calc()}
function mode(m){document.querySelectorAll('.mode-tab').forEach(b=>{const on=b.dataset.mode===m;b.classList.toggle('active',on);b.setAttribute('aria-selected',on)});$('modeHelp').textContent=m==='verify'?(L==='zh'?'验证现有链路是否满足设备光功率预算。':'Verify whether an existing link meets the equipment power budget.'):(L==='zh'?'根据设备预算和固定损耗反推最大光纤距离。':'Estimate maximum fiber distance from equipment budget and fixed losses.');calc()}
function invalidate(){
 last=null;
 ["standardOdnBudget","rawChannelWindow","opticalPenaltyResult","physicalLoss","designLoss","remainingBudget","estimatedRx","sensitivityMargin","overloadMargin","maxDistance","fiberLoss","spliceTotal","connectorTotal","splitterTotal","otherLossResult","marginResult","txEcho","sensEcho"].forEach(id=>$(id).textContent="—");
 $("summaryCard").className="summary-card";$("healthBadge").textContent=L==="zh"?"输入无效":"Invalid input";
 $("diagnosis").className="diagnosis";$("diagnosisText").textContent=TXT[L].invalid;
 $("budgetUsed").style.width="0%";$("budgetUsed").className="budget-used";$("budgetUsage").textContent="—";
 ["copyBtn","saveBtn","csvBtn"].forEach(id=>$(id).disabled=true);
}
function calc(){
 const v={project:$("projectName").value.trim()||"Untitled",mode:document.querySelector(".mode-tab.active").dataset.mode,tx:num("txPower"),txMax:num("txMaxPower"),sens:num("rxSensitivity"),over:num("rxOverload"),penalty:num("opticalPenalty"),d:num("distance"),a:num("attenuation"),sc:num("spliceCount"),sl:num("spliceLoss"),cc:num("connectorCount"),cl:num("connectorLoss"),s1:num("splitter1"),s2:num("splitter2"),s3:num("splitter3"),other:num("otherLoss"),margin:num("engineeringMargin"),wave:$("wavelength").value};
 const result=window.NELOpticalPowerBudgetEngine.calculate(v);
 if(!result.ok){invalidate();$("validation").textContent=TXT[L].invalid+(L==="zh"?" 光纤衰减系数必须大于 0。":" Fiber attenuation must be greater than 0.");return}
 $("validation").textContent="";
 const {raw,standard,fiber,splice,conn,split,fixed,physical,design,remain,rx,rxMax,sensM,overM,maxD,st,usage}=result;
 last={...v,raw,standard,fiber,splice,conn,split,fixed,physical,design,remain,rx,rxMax,sensM,overM,maxD,st,time:new Date().toISOString()};
 [["standardOdnBudget",standard],["rawChannelWindow",raw],["opticalPenaltyResult",v.penalty],["physicalLoss",physical],["designLoss",design],["remainingBudget",remain],["sensitivityMargin",sensM],["overloadMargin",overM],["maxDistance",maxD],["fiberLoss",fiber],["spliceTotal",splice],["connectorTotal",conn],["splitterTotal",split],["otherLossResult",v.other],["marginResult",v.margin],["txEcho",v.tx],["sensEcho",v.sens]].forEach(x=>set(...x));
 $("estimatedRx").textContent=`${rx.toFixed(2)} to ${rxMax.toFixed(2)}`;
 ["copyBtn","saveBtn","csvBtn"].forEach(id=>$(id).disabled=false);
 const sum=$("summaryCard"),diag=$("diagnosis"),bar=$("budgetUsed");
 sum.className="summary-card "+st;diag.className="diagnosis "+st;$("healthBadge").textContent=TXT[L][st];
 $("diagnosisText").textContent=st==="healthy"?TXT[L].ok:st==="warning"?TXT[L].warn:TXT[L].fail;
 bar.style.width=Math.min(100,usage)+"%";bar.className="budget-used "+(st==="healthy"?"":st);$("budgetUsage").textContent=usage.toFixed(1)+"%";
 window.nelTrack?.("optical_budget_calculate",{status:st,mode:v.mode,wavelength:String(v.wave),design_loss:+design.toFixed(2),remaining_budget:+remain.toFixed(2)});
}
function reset(){Object.assign($('preset'),{value:'gpon-c'});$('projectName').value='GPON C+ 1:64 Optical Budget';$('txPower').value=3;$('txMaxPower').value=7;$('rxSensitivity').value=-30;$('rxOverload').value=-8;$('opticalPenalty').value=1;$('distance').value=10;$('wavelength').value='1490';setAtt();$('spliceCount').value=6;$('spliceLoss').value=.1;$('connectorCount').value=4;$('connectorLoss').value=.3;$('splitter1').value='10.5';$('splitter2').value='10.5';$('splitter3').value='0';$('otherLoss').value=0;$('engineeringMargin').value=3;mode('verify')}
function report(){if(!last)calc();if(!last)return null;const r=last;return [`NetEngineerLab - Optical Power Budget Calculator`,`${L==='zh'?'工程':'Project'}: ${r.project}`,`${L==='zh'?'标准ODN预算':'Standard ODN budget'}: ${r.standard.toFixed(2)} dB`,`${L==='zh'?'原始收发窗口':'Raw Tx/Rx window'}: ${r.raw.toFixed(2)} dB`,`${L==='zh'?'系统光学代价':'Optical path penalty'}: ${r.penalty.toFixed(2)} dB`,`${L==='zh'?'物理链路损耗':'Physical loss'}: ${r.physical.toFixed(2)} dB`,`${L==='zh'?'总设计损耗':'Design loss'}: ${r.design.toFixed(2)} dB`,`${L==='zh'?'剩余预算':'Remaining budget'}: ${r.remain.toFixed(2)} dB`,`${L==='zh'?'预计接收光功率范围':'Estimated receive-power range'}: ${r.rx.toFixed(2)} to ${r.rxMax.toFixed(2)} dBm`,`${L==='zh'?'最大估算距离':'Estimated maximum distance'}: ${r.maxD.toFixed(2)} km`,`${L==='zh'?'状态':'Status'}: ${TXT[L][r.st]}`].join('\n')}
function temp(btn,msg){const old=btn.innerHTML;btn.textContent=msg;setTimeout(()=>btn.innerHTML=old,1300)}async function copy(){const t=report();if(!t)return;try{await navigator.clipboard.writeText(t)}catch{const a=document.createElement('textarea');a.value=t;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}temp($('copyBtn'),TXT[L].copied);window.nelTrack?.('optical_budget_copy')}
function hist(){try{return JSON.parse(localStorage.getItem('opticalBudgetHistory')||'[]')}catch{return[]}}function save(){if(!last)calc();if(!last)return;const h=hist();h.unshift(last);localStorage.setItem('opticalBudgetHistory',JSON.stringify(h.slice(0,12)));render();temp($('saveBtn'),TXT[L].saved);window.nelTrack?.('optical_budget_save')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function render(){const h=hist(),c=$('historyList');if(!h.length){c.innerHTML=`<div class="history-empty">${TXT[L].empty}</div>`;return}c.innerHTML=h.slice(0,6).map(r=>`<article class="history-item"><h3>${esc(r.project)}</h3><p>${new Date(r.time).toLocaleString(L==='zh'?'zh-CN':'en-US')}</p><p>${L==='zh'?'设计损耗':'Design loss'}: <strong>${r.design.toFixed(2)} dB</strong></p><p>${L==='zh'?'剩余预算':'Remaining'}: ${r.remain.toFixed(2)} dB</p><p>${TXT[L][r.st]}</p></article>`).join('')}
function csv(){if(!last)calc();if(!last)return;const r=last,rows=[['Project',r.project],['Minimum Tx Power dBm',r.tx],['Maximum Tx Power dBm',r.txMax],['Receiver Sensitivity dBm',r.sens],['Overload Threshold dBm',r.over],['Raw Tx/Rx Window dB',r.raw.toFixed(2)],['Optical Path Penalty dB',r.penalty.toFixed(2)],['Standard ODN Budget dB',r.standard.toFixed(2)],['Physical Loss dB',r.physical.toFixed(2)],['Design Loss dB',r.design.toFixed(2)],['Remaining Budget dB',r.remain.toFixed(2)],['Estimated Minimum RX dBm',r.rx.toFixed(2)],['Estimated Maximum RX dBm',r.rxMax.toFixed(2)],['Maximum Distance km',r.maxD.toFixed(2)],['Status',TXT[L][r.st]]],text='\uFEFF'+rows.map(row=>row.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'),b=new Blob([text],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='optical_power_budget_report.csv';a.click();URL.revokeObjectURL(a.href);temp($('csvBtn'),TXT[L].downloaded)}
['projectName','distance','attenuation','spliceCount','spliceLoss','connectorCount','connectorLoss','splitter1','splitter2','splitter3','otherLoss','opticalPenalty','engineeringMargin','txPower','txMaxPower','rxSensitivity','rxOverload'].forEach(id=>$(id).addEventListener('input',()=>{invalidate();clearTimeout(window.__t);window.__t=setTimeout(calc,150)}));$('wavelength').addEventListener('change',()=>{setAtt();calc()});$('preset').addEventListener('change',preset);document.querySelectorAll('.mode-tab').forEach(b=>b.addEventListener('click',()=>mode(b.dataset.mode)));$('calculateBtn').onclick=calc;$('resetBtn').onclick=reset;$('copyBtn').onclick=copy;$('saveBtn').onclick=save;$('csvBtn').onclick=csv;$('printBtn').onclick=()=>{window.nelTrack?.('optical_budget_print');print()};$('clearHistoryBtn').onclick=()=>{if(confirm(TXT[L].clear)){localStorage.removeItem('opticalBudgetHistory');render()}};setAtt();calc();render();
