(function(){
  "use strict";
  const lang=window.NEL_LANG==="zh"?"zh":"en",engine=window.NetEngineerLabAclEngine,irApi=window.NetEngineerLabAclIr,bundle=window.NetEngineerLabRulesBundle;
  const text={en:{ready:"Paste a supported ACL or build one from parameters. Processing stays in this browser.",working:"Analyzing configuration…",complete:(p,u)=>`Parsed ${p} rule(s); ${u} unsupported line(s).`,noFindings:"No high-confidence findings matched. This is not proof that the ACL is safe or complete.",findings:n=>`${n} deterministic finding(s) matched.`,error:"The configuration could not be analyzed. Check the selected vendor and supported V1 syntax.",errorCoverage:"No current result — the latest input was rejected.",emptyOutput:"No current generated configuration.",evidence:"Evidence",reason:"Why it matters",recommendation:"Recommendation",experience:"Field note",references:"References",copied:"Generated configuration copied.",copyFailed:"Copy was not available; select the generated text manually.",generated:"Configuration generated and semantic round-trip verified.",unsupported:"Unsupported lines remain; findings cover only parsed rules.",remove:"Remove rule",fields:["Seq","Action","Protocol","Source","Destination","Port","Log"],sourceHelp:"Use any, host 10.0.0.1, or 10.0.0.0/8.",local:"Local-only: configuration and findings are not sent to AI or analytics."},zh:{ready:"粘贴受支持的 ACL，或通过参数构建。所有处理均在当前浏览器本地完成。",working:"正在分析配置……",complete:(p,u)=>`已解析 ${p} 条规则；${u} 行语法不受支持。`,noFindings:"未命中高可信规则。这不代表 ACL 已被证明安全或完整。",findings:n=>`命中 ${n} 条确定性检查结果。`,error:"无法分析该配置，请核对厂商选择和 V1 支持语法。",errorCoverage:"无当前结果——最新输入已被拒绝。",emptyOutput:"当前没有生成的配置。",evidence:"证据",reason:"风险原因",recommendation:"建议",experience:"现场说明",references:"参考资料",copied:"已复制生成的配置。",copyFailed:"无法自动复制，请手动选择生成内容。",generated:"配置已生成，并通过语义往返验证。",unsupported:"仍有不受支持的行；检查结果仅覆盖已解析规则。",remove:"删除规则",fields:["序号","动作","协议","源","目的","端口","日志"],sourceHelp:"支持 any、host 10.0.0.1 或 10.0.0.0/8。",local:"仅本地处理：配置与检查结果不会发送给 AI 或分析系统。"}}[lang];
  const $=id=>document.getElementById(id),status=$("statusPanel"),findings=$("findings"),output=$("generatedOutput"),rows=$("ruleRows");
  const samples={"cisco-ios":"ip access-list extended EDGE-IN\n 10 permit tcp 10.10.0.0 0.0.255.255 any eq 443 log\n 20 deny ip any any log\nexit\n","huawei-vrp":"acl name EDGE-IN advance\n rule 10 permit tcp source 10.10.0.0 0.0.255.255 destination any destination-port eq 443 logging\n rule 20 deny ip source any destination any logging\nquit\n","h3c-comware":"acl advanced name EDGE-IN\n rule 10 permit tcp source 10.10.0.0 0.0.255.255 destination any destination-port eq 443 logging\n rule 20 deny ip source any destination any logging\nquit\n","juniper-junos":"set firewall family inet filter EDGE-IN term rule-10 from protocol tcp\nset firewall family inet filter EDGE-IN term rule-10 from source-address 10.10.0.0/16\nset firewall family inet filter EDGE-IN term rule-10 from destination-port 443\nset firewall family inet filter EDGE-IN term rule-10 then log\nset firewall family inet filter EDGE-IN term rule-10 then accept\nset firewall family inet filter EDGE-IN term rule-20 then log\nset firewall family inet filter EDGE-IN term rule-20 then discard\n","arista-eos":"ip access-list EDGE-IN\n 10 permit tcp 10.10.0.0/16 any eq 443 log\n 20 deny ip any any log\nexit\n"};
  function setStatus(message,tone="info"){status.textContent=message;status.dataset.tone=tone}
  function clearResult(){$("coverage").textContent=text.errorCoverage;$("score").textContent="—";for(const level of ["CRITICAL","HIGH","MEDIUM","INFO"])$(`count${level}`).textContent="0";$("scoreDisclaimer").textContent="";findings.replaceChildren();output.textContent=text.emptyOutput}
  function safeError(){clearResult();setStatus(text.error,"error")}
  function display(value){return typeof value==="object"&&value!==null?JSON.stringify(value):String(value)}
  function render(result){
    const coverage=result.parsed.coverage;$("coverage").textContent=text.complete(coverage.parsedRules,coverage.unparsedLines);$("coverage").dataset.incomplete=String(!coverage.complete);
    $("score").textContent=String(result.score.overall);for(const level of ["CRITICAL","HIGH","MEDIUM","INFO"])$(`count${level}`).textContent=String(result.score.counts[level]);
    $("scoreDisclaimer").textContent=result.score.disclaimer[lang];findings.replaceChildren();
    if(!result.findings.length){const p=document.createElement("p");p.textContent=text.noFindings;findings.append(p)}
    for(const finding of result.findings){const article=document.createElement("article");article.className="finding";article.dataset.severity=finding.severity;const header=document.createElement("div");header.className="finding-header";const title=document.createElement("h3");title.textContent=`${finding.ruleId} — ${finding.title}`;const severity=document.createElement("span");severity.className="severity";severity.textContent=finding.severity;header.append(title,severity);article.append(header);
      for(const [label,value] of [["",finding.finding],[text.reason,finding.reason],[text.recommendation,finding.recommendation],[text.experience,finding.fieldExperienceNote]]){const p=document.createElement("p");if(label){const strong=document.createElement("strong");strong.textContent=`${label}: `;p.append(strong)}p.append(document.createTextNode(value));article.append(p)}
      const details=document.createElement("details"),summary=document.createElement("summary"),dl=document.createElement("dl");summary.textContent=text.evidence;for(const item of finding.evidence){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=item.field;dd.textContent=display(item.value);dl.append(dt,dd)}details.append(summary,dl);article.append(details);
      const rule=bundle.rules.find(item=>item.id===finding.ruleId);if(rule){const refs=document.createElement("p"),strong=document.createElement("strong");strong.textContent=`${text.references}: `;refs.append(strong);rule.references.forEach((reference,index)=>{const a=document.createElement("a");a.href=reference.url;a.rel="noopener noreferrer";a.textContent=reference.title;if(index)refs.append(document.createTextNode(" · "));refs.append(a)});article.append(refs)}findings.append(article)}
    setStatus(coverage.complete?(result.findings.length?text.findings(result.findings.length):text.noFindings):text.unsupported,coverage.complete?"info":"warning");return result;
  }
  function analyze(){setStatus(text.working);const result=engine.analyzeConfiguration({vendor:$("sourceVendor").value,input:$("configuration").value,bundle,locale:lang});return render(result)}
  function endpoint(value){const clean=value.trim().toLowerCase();if(clean==="any")return {kind:"any"};if(clean.startsWith("host "))return {kind:"host",address:clean.slice(5).trim()};const parts=clean.split("/");if(parts.length===2)return {kind:"network",address:parts[0],prefix:Number(parts[1])};return {kind:"host",address:clean}}
  function addRule(values={}){const row=document.createElement("div");row.className="rule-row";const fields=[{key:"sequence",type:"number",value:values.sequence??(rows.children.length+1)*10},{key:"action",options:[["permit","permit"],["deny","deny"]],value:values.action||"permit"},{key:"protocol",options:[["ip","ip"],["tcp","tcp"],["udp","udp"],["icmp","icmp"]],value:values.protocol||"tcp"},{key:"source",value:values.source||"any"},{key:"destination",value:values.destination||"any"},{key:"port",type:"number",value:values.port??443},{key:"log",type:"checkbox",checked:values.log??true}];fields.forEach((field,index)=>{const label=document.createElement("label");label.textContent=text.fields[index];let control;if(field.options){control=document.createElement("select");field.options.forEach(([value,labelText])=>{const option=document.createElement("option");option.value=value;option.textContent=labelText;control.append(option)});control.value=field.value}else{control=document.createElement("input");control.type=field.type||"text";if(field.type==="checkbox")control.checked=field.checked;else control.value=field.value}control.dataset.field=field.key;label.append(control);row.append(label)});const remove=document.createElement("button");remove.type="button";remove.textContent="×";remove.title=text.remove;remove.setAttribute("aria-label",text.remove);remove.addEventListener("click",()=>row.remove());row.append(remove);rows.append(row)}
  function build(){const rules=[...rows.children].map(row=>{const value=key=>row.querySelector(`[data-field="${key}"]`);const protocol=value("protocol").value,port=value("port").value.trim();return {sequence:Number(value("sequence").value),action:value("action").value,protocol,source:endpoint(value("source").value),destination:endpoint(value("destination").value),...(port&&["tcp","udp"].includes(protocol)?{destinationPort:Number(port)}:{}),log:value("log").checked}});const ir=irApi.createIr({name:$("aclName").value,rules});const target=$("targetVendor").value,roundTrip=engine.semanticRoundTrip({vendor:target,ir});if(!roundTrip.equivalent)throw new Error("semantic_round_trip_failed");output.textContent=roundTrip.configuration;setStatus(text.generated);return roundTrip}
  $("loadSample").addEventListener("click",()=>{$("configuration").value=samples[$("sourceVendor").value];setStatus(text.ready)});$("validate").addEventListener("click",()=>{try{analyze()}catch(error){safeError(error)}});$("convert").addEventListener("click",()=>{try{const result=analyze(),roundTrip=engine.semanticRoundTrip({vendor:$("targetVendor").value,ir:result.parsed.ir});if(!roundTrip.equivalent)throw new Error("semantic_round_trip_failed");output.textContent=roundTrip.configuration}catch(error){safeError(error)}});$("addRule").addEventListener("click",()=>addRule({port:""}));$("build").addEventListener("click",()=>{try{build()}catch(error){safeError(error)}});$("copyOutput").addEventListener("click",async()=>{try{await navigator.clipboard.writeText(output.textContent);setStatus(text.copied)}catch{setStatus(text.copyFailed,"warning")}});
  addRule({sequence:10,action:"permit",protocol:"tcp",source:"10.10.0.0/16",destination:"any",port:443,log:true});addRule({sequence:20,action:"deny",protocol:"ip",source:"any",destination:"any",port:"",log:true});$("configuration").value=samples["cisco-ios"];$("localNotice").textContent=text.local;setStatus(text.ready);
})();
