(function(){
  "use strict";
  const $=id=>document.getElementById(id), lang=(document.documentElement.lang||"").startsWith("zh")?"zh":"en";
  const num=id=>Number($(id)?.value||0), fmt=(v,d=2)=>Number(v).toLocaleString(undefined,{maximumFractionDigits:d});
  function collect(){const b={ratedKW:num("ratedKW"),ratedKVA:num("ratedKVA"),powerFactor:num("powerFactor"),fuel0:num("fuel0"),fuel25:num("fuel25"),fuel50:num("fuel50"),fuel75:num("fuel75"),fuel100:num("fuel100"),segments:[1,2,3,4].map(x=>({name:$(`segName${x}`)?.value||`Period ${x}`,loadKW:num(`segLoad${x}`),hours:num(`segHours${x}`)})).filter(s=>s.hours>0),tankLiters:num("tankLiters"),reservePct:num("reservePct"),unusableLiters:num("unusableLiters"),targetHours:num("targetHours"),fuelPrice:num("fuelPrice"),co2KgPerLiter:num("co2Factor"),generatorCount:num("generatorCount"),rotationHours:num("rotationHours"),batteryUsableKWh:num("batteryKWh"),batteryDischargeEfficiencyPct:num("batteryEff"),ambientTempC:num("ambientTempC"),altitudeM:num("altitudeM"),minimumLoadPct:num("minimumLoadPct")||25,wetStackHoursThreshold:num("wetStackHoursThreshold")||4,redundantGen:num("redundantGen"),requiredGenerators:num("requiredGenerators")||1,startFailurePct:num("startFailurePct")||2};return {...b,before:{...b,generatorCount:num("beforeGeneratorCount")||b.generatorCount,redundantGen:num("beforeRedundantGen")},after:{...b,generatorCount:num("afterGeneratorCount")||b.generatorCount,redundantGen:num("afterRedundantGen")}};}
  function set(id,value){if($(id))$(id).textContent=value;}
  function download(name,text,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function extras(r){let box=$("engineeringExtras");if(!box){box=document.createElement("section");box.id="engineeringExtras";box.className="panel";$("result")?.appendChild(box);}const zh=lang==="zh",ba=r.beforeAfter;box.innerHTML=`<h2>${zh?"工程门禁与方案比较":"Engineering gates & scenario comparison"}</h2><div class="kv"><span>${zh?"风险等级":"Risk level"}</span><b>${r.risk} (${r.riskScore})</b></div><div class="kv"><span>${zh?"N-1可用容量":"N-1 available capacity"}</span><b>${fmt(r.nMinus1Capacity,1)} kW — ${r.nMinus1Pass?"PASS":"FAIL"}</b></div><div class="kv"><span>${zh?"环境降额":"Environmental derating"}</span><b>${fmt(r.environment.totalDeratePct,1)}%</b></div><div class="kv"><span>${zh?"湿堆风险":"Wet-stack risk"}</span><b>${r.wetStackRisk}</b></div>${ba&&ba.ok?`<div class="kv"><span>${zh?"Before / After 油耗":"Before / After fuel"}</span><b>${fmt(ba.before.fuel,1)} → ${fmt(ba.after.fuel,1)} L (${fmt(ba.delta.fuel,1)} L)</b></div><div class="kv"><span>${zh?"Before / After N-1 容量":"Before / After N-1 capacity"}</span><b>${fmt(ba.before.capacity,1)} → ${fmt(ba.after.capacity,1)} kW (${fmt(ba.delta.capacity,1)} kW)</b></div><div class="kv"><span>${zh?"Before / After 续航":"Before / After runtime"}</span><b>${fmt(ba.before.runtime,1)} → ${fmt(ba.after.runtime,1)} h (${fmt(ba.delta.runtime,1)} h)</b></div>`:`<p>${zh?"请输入有效的 Before / After 方案以显示差异。":"Enter valid Before / After plans to display the delta."}</p>`}<p>${r.scenarios.map(s=>`${s.name}: ${fmt(s.targetFuel,1)} L, ${s.risk}`).join(" | ")}</p><button type="button" class="btn" id="downloadJson">${zh?"下载JSON工程报告":"Download JSON report"}</button> <button type="button" class="btn" id="downloadCsv">${zh?"下载CSV校核表":"Download CSV check sheet"}</button>`;$("downloadJson").onclick=()=>download("generator-fuel-engineering-report.json",window.NELGeneratorFuelEngine.toJSONReport(r),"application/json");$("downloadCsv").onclick=()=>download("generator-fuel-check-sheet.csv",window.NELGeneratorFuelEngine.toCSV(r),"text/csv");}
  function calc(){const r=window.NELGeneratorFuelEngine.calculate(collect());$("error").hidden=r.ok;if(!r.ok){$("result").hidden=true;return;}$("result").hidden=false;set("avgLoad",`${fmt(r.avgLoadKW,1)} kW`);set("loadPct",`${fmt(r.avgLoadPct,1)}%`);set("fuelRate",`${fmt(r.avgFuelLph,2)} L/h`);set("dailyFuel",`${fmt(r.fuelPerCycle*24/r.totalHours,1)} L/day`);set("runtime",r.runtimeHours==null?"—":`${fmt(r.runtimeHours,1)} h`);set("targetFuel",`${fmt(r.targetFuelWithReserve,1)} L`);set("additionalFuel",`${fmt(r.additionalFuel,1)} L`);set("usableFuel",`${fmt(r.usableFuel,1)} L`);set("specificFuel",r.specificFuel==null?"—":`${fmt(r.specificFuel,3)} L/kWh`);set("targetCost",fmt(r.targetCost,2));set("targetCO2",`${fmt(r.targetCO2,1)} kgCO₂`);set("refills",String(r.refills));set("perUnit",`${fmt(r.perUnitRunHours,1)} h`);set("rotations",String(r.rotations));set("batteryDelay",`${fmt(r.batteryAssistHours,1)} h`);set("fuelAfterBattery",`${fmt(r.fuelAfterBattery,1)} L`);set("fuelSaved",`${fmt(r.batteryFuelSaved,1)} L`);const warnings=[];if(r.warnings.includes("overload"))warnings.push(lang==="zh"?"存在超过额定负载的时段。":"One or more periods exceed rated load.");if(r.warnings.includes("lowLoad"))warnings.push(lang==="zh"?"低负载时段存在湿堆风险。":"Low-load periods may create wet-stacking risk.");if(r.warnings.includes("nMinus1Capacity"))warnings.push(lang==="zh"?"N-1容量校验未通过。":"N-1 capacity check failed.");$("warnings").textContent=warnings.join(" ");$("warnings").hidden=!warnings.length;const body=$("profileBody");if(body){body.innerHTML="";r.profile.forEach(s=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${s.name}</td><td>${fmt(s.loadKW,1)} kW</td><td>${fmt(s.loadPct,1)}%</td><td>${fmt(s.fuelLph,2)} L/h</td><td>${fmt(s.fuelLiters,1)} L</td>`;body.appendChild(tr);});}extras(r);}
  document.querySelectorAll("[data-input]").forEach(e=>e.addEventListener("input",calc));$("calculate")?.addEventListener("click",calc);calc();
})();
