(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;root.NELGeneratorFuelEngine=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
 const n=v=>Number(v), clamp=(v,a,b)=>Math.min(b,Math.max(a,v)), finite=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
 function interpolate(points,loadPct){const p=clamp(loadPct,0,100);for(let x=1;x<points.length;x++){if(p<=points[x][0]){const [x0,y0]=points[x-1],[x1,y1]=points[x];return y0+(y1-y0)*(p-x0)/(x1-x0)}}return points[points.length-1][1]}
 function buildCurve(i){const pts=[[0,finite(i.fuel0,0)],[25,finite(i.fuel25)],[50,finite(i.fuel50)],[75,finite(i.fuel75)],[100,finite(i.fuel100)]];return pts}
 function normalizeSegments(i,ratedKW){let segs=Array.isArray(i.segments)?i.segments:[];segs=segs.map((s,idx)=>({name:s.name||`Period ${idx+1}`,loadKW:Math.max(0,finite(s.loadKW)),hours:clamp(finite(s.hours),0,24)})).filter(s=>s.hours>0);if(!segs.length){segs=[{name:'Current load',loadKW:Math.max(0,finite(i.currentLoadKW)),hours:24}]};return segs.map(s=>({...s,loadPct:ratedKW>0?s.loadKW/ratedKW*100:0}))}
 function fuelForDuration(profile,targetHours){if(!(targetHours>0)||!profile.length)return 0;const cycleHours=profile.reduce((a,s)=>a+s.hours,0);if(!(cycleHours>0))return 0;let remain=targetHours,total=0;while(remain>1e-9){for(const s of profile){if(remain<=0)break;const h=Math.min(remain,s.hours);total+=h*s.fuelLph;remain-=h}if(targetHours>100000&&remain>0)break;}return total}
 function calculate(i={}){
  const errors=[], warnings=[];const pf=clamp(finite(i.powerFactor,0.8),0.1,1);let ratedKW=finite(i.ratedKW);if(!(ratedKW>0)&&finite(i.ratedKVA)>0)ratedKW=finite(i.ratedKVA)*pf;if(!(ratedKW>0))errors.push('ratedPower');
  const curve=buildCurve(i);if(curve.slice(1).some(p=>!(p[1]>0)))errors.push('fuelCurve');for(let x=2;x<curve.length;x++)if(curve[x][1]<curve[x-1][1])warnings.push('nonMonotonicCurve');
  if(errors.length)return{ok:false,errors,warnings};
  const segments=normalizeSegments(i,ratedKW);let totalHours=segments.reduce((a,s)=>a+s.hours,0);if(totalHours>24+1e-9)errors.push('profileHours');if(segments.some(s=>s.loadPct>100))warnings.push('overload');if(segments.some(s=>s.loadPct<25&&s.loadKW>0))warnings.push('lowLoad');if(errors.length)return{ok:false,errors,warnings};
  const profile=segments.map(s=>({...s,fuelLph:interpolate(curve,s.loadPct),fuelLiters:interpolate(curve,s.loadPct)*s.hours}));const fuelPerCycle=profile.reduce((a,s)=>a+s.fuelLiters,0);const energyPerCycle=profile.reduce((a,s)=>a+s.loadKW*s.hours,0);const avgLoadKW=totalHours?energyPerCycle/totalHours:0;const avgLoadPct=ratedKW?avgLoadKW/ratedKW*100:0;const avgFuelLph=totalHours?fuelPerCycle/totalHours:0;const specificFuel=energyPerCycle>0?fuelPerCycle/energyPerCycle:null;
  const tank=Math.max(0,finite(i.tankLiters));const reservePct=clamp(finite(i.reservePct,10),0,80);const unusable=Math.max(0,finite(i.unusableLiters));const usableFuel=Math.max(0,tank*(1-reservePct/100)-unusable);const runtimeHours=avgFuelLph>0?usableFuel/avgFuelLph:null;
  const targetHours=Math.max(0,finite(i.targetHours,24));const rawTargetFuel=fuelForDuration(profile,targetHours);const targetFuelWithReserve=rawTargetFuel/(1-reservePct/100||1)+unusable;const additionalFuel=Math.max(0,targetFuelWithReserve-tank);
  const fuelPrice=Math.max(0,finite(i.fuelPrice));const costPerHour=avgFuelLph*fuelPrice;const targetCost=rawTargetFuel*fuelPrice;const co2Factor=Math.max(0,finite(i.co2KgPerLiter,2.68));const targetCO2=rawTargetFuel*co2Factor;
  const generators=Math.max(1,Math.floor(finite(i.generatorCount,1)));const rotationHours=Math.max(0,finite(i.rotationHours,0));const perUnitRunHours=targetHours/generators;const rotations=rotationHours>0?Math.max(0,Math.ceil(targetHours/rotationHours)-1):0;
  const batteryKWh=Math.max(0,finite(i.batteryUsableKWh));const batteryEff=clamp(finite(i.batteryDischargeEfficiencyPct,90),1,100)/100;const batteryAssistHours=avgLoadKW>0?batteryKWh*batteryEff/avgLoadKW:0;const generatorHoursAfterBattery=Math.max(0,targetHours-batteryAssistHours);const fuelAfterBattery=fuelForDuration(profile,generatorHoursAfterBattery);const batteryFuelSaved=Math.max(0,rawTargetFuel-fuelAfterBattery);
  const refills=usableFuel>0&&rawTargetFuel>usableFuel?Math.max(0,Math.ceil(rawTargetFuel/usableFuel)-1):0;
  return{ok:true,warnings,ratedKW,powerFactor:pf,curve,profile,totalHours,energyPerCycle,fuelPerCycle,avgLoadKW,avgLoadPct,avgFuelLph,specificFuel,tank,reservePct,unusable,usableFuel,runtimeHours,targetHours,rawTargetFuel,targetFuelWithReserve,additionalFuel,fuelPrice,costPerHour,targetCost,targetCO2,generators,rotationHours,perUnitRunHours,rotations,refills,batteryKWh,batteryAssistHours,generatorHoursAfterBattery,fuelAfterBattery,batteryFuelSaved};
 }
 return{calculate,interpolate};});