/** NetEngineerLab | V2.1-Phase2 | Arista EOS IPv4 ACL parser */
(function(root,factory){const api=factory(typeof module==="object"&&module.exports?require("../ir-adapter"):root.NetEngineerLabAclIr);if(typeof module==="object"&&module.exports)module.exports=api;else root.NetEngineerLabAristaEosAclParser=api})(typeof self!=="undefined"?self:this,function(irApi){
  "use strict";
  const MAX_INPUT_BYTES=100*1024,MAX_LINES=2000;
  function utf8Bytes(value){let n=0;for(const c of value){const x=c.codePointAt(0);n+=x<=0x7f?1:x<=0x7ff?2:x<=0xffff?3:4}return n}
  function endpoint(tokens,index){const token=tokens[index];if(token==="any")return {endpoint:{kind:"any"},next:index+1};if(token==="host"&&irApi.parseIpv4(tokens[index+1])!==null)return {endpoint:{kind:"host",address:tokens[index+1]},next:index+2};const cidr=/^(\d{1,3}(?:\.\d{1,3}){3})\/(\d|[12]\d|3[0-2])$/.exec(token||"");if(cidr&&irApi.parseIpv4(cidr[1])!==null)return {endpoint:Number(cidr[2])===32?{kind:"host",address:cidr[1]}:{kind:"network",address:cidr[1],prefix:Number(cidr[2])},next:index+1};return null}
  function parseRule(text,line){const tokens=text.trim().split(/\s+/).map(x=>x.toLowerCase());let i=0,sequence;if(/^\d+$/.test(tokens[0])){sequence=Number(tokens[i++]);if(sequence<1)return null}const action=tokens[i++],protocol=tokens[i++];if(!["permit","deny"].includes(action)||!["ip","tcp","udp","icmp"].includes(protocol))return null;const source=endpoint(tokens,i);if(!source)return null;i=source.next;const destination=endpoint(tokens,i);if(!destination)return null;i=destination.next;let destinationPort,log=false;if(tokens[i]==="eq"){destinationPort=tokens[i+1];if(!/^\d+$/.test(destinationPort||"")||Number(destinationPort)>65535)return null;i+=2}if(tokens[i]==="log"){log=true;i++}if(i!==tokens.length)return null;return {sequence,action,protocol,source:source.endpoint,destination:destination.endpoint,...(destinationPort===undefined?{}:{destinationPort}),log,sourceLine:line,raw:text}}
  function parse(input){const text=String(input??"");if(utf8Bytes(text)>MAX_INPUT_BYTES)throw new Error("acl_input_too_large");if(text.includes("\0"))throw new Error("acl_input_contains_nul");const lines=text.replace(/\r\n?/g,"\n").split("\n");if(lines.length>MAX_LINES)throw new Error("acl_too_many_lines");let name=null,inAcl=false;const rules=[],warnings=[],unparsed=[];lines.forEach((raw,offset)=>{const line=offset+1,s=raw.trim();if(!s||s.startsWith("!"))return;const h=/^ip access-list ([A-Za-z][A-Za-z0-9_.-]{0,63})$/i.exec(s);if(h){if(name!==null)throw new Error("multiple_acls_not_supported");name=h[1];inAcl=true;return}if(/^(?:exit|end)$/i.test(s)){inAcl=false;return}if(!inAcl){unparsed.push({line,text:raw,code:"outside_acl"});return}if(/^remark(?:\s|$)/i.test(s)){warnings.push({code:"remark_ignored",line});return}const rule=parseRule(s,line);if(rule)rules.push(rule);else unparsed.push({line,text:raw,code:"unsupported_syntax"})});if(!name)throw new Error("arista_eos_ipv4_acl_required");if(!rules.length)throw new Error("acl_contains_no_supported_rules");const styles=new Set(rules.map(r=>r.sequence===undefined?"implicit":"explicit"));if(styles.size>1)throw new Error("mixed_sequence_style_not_supported");const ir=irApi.createIr({name,rules,vendor:"arista-eos",sourceType:"configuration"});if(unparsed.length)warnings.push({code:"unsupported_lines_present",count:unparsed.length});return Object.freeze({vendor:"arista-eos",ir,warnings:Object.freeze(warnings),unparsed:Object.freeze(unparsed),coverage:Object.freeze({parsedRules:rules.length,unparsedLines:unparsed.length,complete:unparsed.length===0})})}
  return Object.freeze({MAX_INPUT_BYTES,MAX_LINES,parse,parseRule,utf8Bytes});
});
