(()=>{'use strict';const $=id=>document.getElementById(id),zh=document.documentElement.lang.startsWith('zh');const labels=zh?{healthy:'健康',warning:'关注',high:'高风险',critical:'容量失败',low:'低',moderate:'中等',elevated:'较高',fabric:'接入/Leaf Fabric',upper:'上层/核心',egress:'南北向出口',copied:'结果已复制',invalid:'请检查输入值，故障节点数必须小于中间层节点数。'}:{healthy:'Healthy',warning:'Review',high:'High risk',critical:'Capacity failure',low:'Low',moderate:'Moderate',elevated:'Elevated',fabric:'Access / leaf fabric',upper:'Upper / core layer',egress:'North-south egress',copied:'Result copied',invalid:'Check the inputs. Failed middle-layer nodes must be fewer than installed nodes.'};
const ids=['topology','edgeCount','portsPerEdge','portGbps','utilizationPct','concurrencyPct','allowancePct','edgeUplinks','edgeUplinkGbps','middleCount','upperLinksPerMiddle','upperLinkGbps','egressLinks','egressLinkGbps','eastWestPct','crossEdgePct','eastWestUpperPct','targetUtilizationPct','annualGrowthPct','failedMiddleNodes'];
function input(){return Object.fromEntries(ids.map(id=>[id,$(id).value]));}
function fmt(v,d=1){return Number.isFinite(+v)?Number(v).toFixed(d).replace(/\.0$/,''):'—';}
function ratio(v){return `${fmt(v,2)} : 1`;}
function set(id,v){const e=$(id);if(e)e.textContent=v;}
function applyPreset(name){const p={leaf25:{topology:'leaf-spine',edgeCount:8,portsPerEdge:48,portGbps:25,utilizationPct:35,concurrencyPct:70,allowancePct:20,edgeUplinks:4,edgeUplinkGbps:100,middleCount:4,upperLinksPerMiddle:2,upperLinkGbps:100,egressLinks:4,egressLinkGbps:100,eastWestPct:70,crossEdgePct:75,eastWestUpperPct:0,targetUtilizationPct:70,annualGrowthPct:20,failedMiddleNodes:1},gpu:{topology:'leaf-spine',edgeCount:16,portsPerEdge:32,portGbps:100,utilizationPct:55,concurrencyPct:85,allowancePct:25,edgeUplinks:8,edgeUplinkGbps:400,middleCount:8,upperLinksPerMiddle:2,upperLinkGbps:400,egressLinks:8,egressLinkGbps:400,eastWestPct:90,crossEdgePct:90,eastWestUpperPct:0,targetUtilizationPct:65,annualGrowthPct:30,failedMiddleNodes:1},three:{topology:'three-tier',edgeCount:24,portsPerEdge:48,portGbps:10,utilizationPct:30,concurrencyPct:65,allowancePct:20,edgeUplinks:2,edgeUplinkGbps:40,middleCount:4,upperLinksPerMiddle:4,upperLinkGbps:100,egressLinks:8,egressLinkGbps:100,eastWestPct:55,crossEdgePct:70,eastWestUpperPct:40,targetUtilizationPct:70,annualGrowthPct:15,failedMiddleNodes:1}}[name];if(!p)return;Object.entries(p).forEach(([k,v])=>{$(k).value=v});updateLabels();calc();}
function updateLabels(){const leaf=$('topology').value==='leaf-spine';set('edgeLabel',leaf?(zh?'Leaf 交换机数量':'Leaf switches'):(zh?'接入交换机数量':'Access switches'));set('middleLabel',leaf?(zh?'Spine 数量':'Spine switches'):(zh?'汇聚交换机数量':'Aggregation switches'));set('upperLinksLabel',leaf?(zh?'每台 Spine 至核心/边界链路':'Core/border links per spine'):(zh?'每台汇聚至核心链路':'Core links per aggregation'));set('ewUpperHelp',leaf?(zh?'Leaf-Spine 一般填 0%；只有东西向流量继续穿越更上层时才增加。':'Usually 0% in a two-tier leaf-spine fabric; increase only when east-west traffic traverses an upper tier.'):(zh?'估算跨接入东西向流量中需要继续经过核心层的比例。':'Share of cross-access east-west traffic that must continue through the core layer.'));}
function recommendationText(r){const lines=[];const z=zh;if(!r.recommendations.length)lines.push(z?'当前正常、故障及增长场景均在目标阈值内。':'Normal, failure and growth scenarios are within the target threshold.');if(r.recommendations.includes('fabric-capacity'))lines.push(z?`接入 Fabric 容量不足，建议每台边缘节点至少 ${r.minEdgeUplinks} 条现有速率上联，或提升单链路速率。`:`Fabric capacity is constrained. Use at least ${r.minEdgeUplinks} uplinks per edge node at the entered speed, or increase link speed.`);if(r.recommendations.includes('upper-capacity'))lines.push(z?`上层容量不足，建议每台中间层节点至少 ${r.minUpperLinksPerMiddle} 条现有速率上联。`:`Upper-layer capacity is constrained. Use at least ${r.minUpperLinksPerMiddle} upper links per middle-layer node at the entered speed.`);if(r.recommendations.includes('egress-capacity'))lines.push(z?`南北向出口容量不足，建议至少 ${r.minEgressLinks} 条现有速率出口链路。`:`North-south egress is constrained. Use at least ${r.minEgressLinks} egress links at the entered speed.`);if(r.recommendations.includes('n1-fail'))lines.push(z?'N-1 后容量超过 100%，故障场景会发生硬性容量缺口，应优先扩容或增加中间层节点。':'N-1 exceeds 100% utilization, creating a hard capacity deficit. Add capacity or another middle-layer node before relying on this redundancy model.');else if(r.recommendations.includes('n1-headroom'))lines.push(z?'N-1 虽未超过物理容量，但已高于目标利用率，故障时缺少工程余量。':'N-1 remains below physical capacity but exceeds the target utilization, leaving inadequate failure headroom.');if(r.recommendations.includes('growth'))lines.push(z?'按当前增长率，3 年场景将超过目标阈值，应提前规划升级窗口。':'At the entered growth rate, the 3-year projection exceeds the target; schedule an upgrade before that point.');return lines;}
function calc(){const r=window.NELDataCenterFabricEngine.calculate(input());$('error').hidden=!!r.ok;if(!r.ok){$('error').textContent=labels.invalid;return;}window.lastResult=r;set('designStatus',labels[r.designStatus]);$('designStatus').className='status '+r.designStatus;set('riskScore',`${r.riskScore}/100 · ${labels[r.riskLevel]||r.riskLevel}`);set('lineRate',`${fmt(r.lineRateGbps)} Gbps`);set('busyDemand',`${fmt(r.busyDemandGbps)} Gbps`);set('eastWest',`${fmt(r.eastWestGbps)} Gbps`);set('northSouth',`${fmt(r.northSouthGbps)} Gbps`);set('fabricCapacity',`${fmt(r.fabricCapacityGbps)} Gbps`);set('upperCapacity',`${fmt(r.upperCapacityGbps)} Gbps`);set('egressCapacity',`${fmt(r.egressCapacityGbps)} Gbps`);set('layer1Conv',ratio(r.layer1Convergence));set('layer2Conv',ratio(r.layer2Convergence));set('totalConv',ratio(r.totalConvergence));set('fabricUtil',`${fmt(r.fabricUtilPct)}%`);set('upperUtil',`${fmt(r.upperUtilPct)}%`);set('egressUtil',`${fmt(r.egressUtilPct)}%`);set('n1Fabric',`${fmt(r.n1FabricUtilPct)}%`);set('n1Upper',`${fmt(r.n1UpperUtilPct)}%`);set('bottleneck',labels[r.normalBottleneck]);set('n1Bottleneck',labels[r.failureBottleneck]);set('survivingMiddle',`${r.survivingMiddle}`);set('minEdgeUplinks',`${r.minEdgeUplinks}`);set('minUpperLinks',`${r.minUpperLinksPerMiddle}`);set('minEgressLinks',`${r.minEgressLinks}`);
 const tbody=$('growthRows');tbody.innerHTML=r.projections.map(p=>`<tr><td>Y${p.year}</td><td>${fmt(p.demandGbps)} Gbps</td><td>${fmt(p.fabricUtilPct)}%</td><td>${fmt(p.upperUtilPct)}%</td><td>${fmt(p.egressUtilPct)}%</td><td><span class="mini ${p.status}">${labels[p.status]}</span></td></tr>`).join('');
 $('recommendations').innerHTML=recommendationText(r).map(x=>`<li>${x}</li>`).join('');
 const bars=[['fabricBar',r.fabricUtilPct],['upperBar',r.upperUtilPct],['egressBar',r.egressUtilPct],['n1FabricBar',r.n1FabricUtilPct]];bars.forEach(([id,v])=>{$(id).style.width=`${Math.min(100,v)}%`;$(id).dataset.over=v>100?'1':'0'});
}
ids.forEach(id=>$(id).addEventListener(id==='topology'?'change':'input',()=>{if(id==='topology')updateLabels();calc();}));document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));$('copy').addEventListener('click',async()=>{const r=window.lastResult;if(!r)return;const t=`${zh?'数据中心 Fabric 规划':'Data Center Fabric Plan'}\n${zh?'状态':'Status'}: ${labels[r.designStatus]}\n${zh?'总收敛比':'Total convergence'}: ${ratio(r.totalConvergence)}\n${zh?'Fabric 利用率':'Fabric utilization'}: ${r.fabricUtilPct}%\nN-1: ${r.n1FabricUtilPct}%\n${zh?'风险':'Risk'}: ${r.riskScore}/100`;try{await navigator.clipboard.writeText(t);$('copy').textContent=labels.copied;setTimeout(()=>location.reload?$('copy').textContent=(zh?'复制结果':'Copy result'):0,1200)}catch{}});$('print').addEventListener('click',()=>window.print());updateLabels();calc();})();
