(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.NELRackEngine=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const rd=(v,d=2)=>Number(v.toFixed(d)); const num=(v,d)=>v===undefined||v===''?(d===undefined?NaN:d):Number(v);
function calculate(i){
 if(!i)return{ok:false,error:'input'};
 const loadW=num(i.loadW),qty=num(i.qty),util=num(i.util)/100,growth=num(i.growth)/100,redundancy=num(i.redundancy)/100,pf=num(i.pf),voltage=num(i.voltage),phases=num(i.phases),breaker=num(i.breaker),hours=num(i.hours),days=num(i.days),rate=num(i.rate),cop=num(i.cop);
 if(![loadW,qty,util,growth,redundancy,pf,voltage,phases,breaker,hours,days,rate,cop].every(Number.isFinite)||!(loadW>0&&qty>0&&util>0&&util<=1&&growth>=0&&redundancy>=0&&pf>0&&pf<=1&&voltage>0&&[1,3].includes(phases)&&breaker>0&&hours>=0&&hours<=24&&days>=0&&days<=31&&rate>=0&&cop>0))return{ok:false,error:'input'};
 const connectedW=loadW*qty,actualW=connectedW*util,designW=actualW*(1+growth)*(1+redundancy),va=designW/pf,current=phases===3?va/(Math.sqrt(3)*voltage):va/voltage,loadPct=current/breaker*100;
 const rackU=num(i.rackU,42),usedU=num(i.usedU,Math.min(rackU,42)),ambientC=num(i.ambientC,24),humidity=num(i.humidity,50),latentPct=num(i.latentPct,10)/100,upsEfficiency=num(i.upsEfficiency,.95),pduEfficiency=num(i.pduEfficiency,.97),coolingRedundancy=num(i.coolingRedundancy,0)/100,feedCount=num(i.feedCount,1),dualPath=String(i.dualPath)==='true'||String(i.dualPath)==='1',n1Units=num(i.n1Units,1);
 if(![rackU,usedU,ambientC,humidity,latentPct,upsEfficiency,pduEfficiency,coolingRedundancy,feedCount,n1Units].every(Number.isFinite)||!(rackU>0&&usedU>0&&usedU<=rackU&&humidity>=0&&humidity<=100&&latentPct>=0&&latentPct<1&&upsEfficiency>0&&upsEfficiency<=1&&pduEfficiency>0&&pduEfficiency<=1&&coolingRedundancy>=0&&feedCount>=1&&Number.isInteger(feedCount)&&n1Units>=1&&Number.isInteger(n1Units)))return{ok:false,error:'input'};
 const heatW=designW/(upsEfficiency*pduEfficiency),sensibleW=heatW*(1-latentPct),latentW=heatW*latentPct,btu=heatW*3.412142,coolingW=heatW/cop,tons=btu/12000,daily=actualW*hours/1000,monthly=daily*days,cost=monthly*rate,density=designW/usedU,n1CoolingW=coolingW*(1+coolingRedundancy),feedLoadPct=loadPct/(dualPath?Math.max(1,feedCount-1):feedCount),risk=[];
 if(loadPct>80)risk.push('electrical-capacity');if(feedCount<2||!dualPath)risk.push('single-path');if(n1Units<2)risk.push('no-n+1');if(density>500)risk.push('high-density');if(ambientC>27)risk.push('high-ambient');
 const status=loadPct<=80?'pass':loadPct<=100?'warning':'fail',before={designW:rd(actualW),coolingW:rd(actualW/(upsEfficiency*pduEfficiency*cop)),loadPct:rd((actualW/pf/(phases===3?Math.sqrt(3)*voltage:voltage))/breaker*100,1)},after={designW:rd(designW),coolingW:rd(n1CoolingW),loadPct:rd(feedLoadPct,1)};
 return{ok:true,connectedW:rd(connectedW),actualW:rd(actualW),designW:rd(designW),designKW:rd(designW/1000),va:rd(va),current:rd(current),loadPct:rd(loadPct,1),btu:rd(btu),sensibleW:rd(sensibleW),latentW:rd(latentW),coolingW:rd(coolingW),n1CoolingW:rd(n1CoolingW),tons:rd(tons,3),daily:rd(daily),monthly:rd(monthly),cost:rd(cost),rackU:rd(rackU),usedU:rd(usedU),density:rd(density),heatW:rd(heatW),feedLoadPct:rd(feedLoadPct,1),n1PowerW:rd(n1Units>1?designW/(n1Units-1):designW),risk,status,before,after,delta:{designW:rd(after.designW-before.designW),coolingW:rd(after.coolingW-before.coolingW),loadPct:rd(after.loadPct-before.loadPct,1)}};
 }
 function toJSON(r){return JSON.stringify(r,null,2)} function toCSV(r){return r&&r.ok?Object.entries(r).filter(([,v])=>typeof v!=='object').map(([k,v])=>k+','+v).join('\n'):''} return{calculate,toJSON,toCSV};});
